window.BASE_CHAPTERS = window.BASE_CHAPTERS || [];
window.BASE_CHAPTERS.push({
  id: "Profit-Loss",
  title: "Profit and Loss",
  desc: "SSC CGL PYQs focused on Profit and Loss.",
  questions: [
  {
    "question_number": 1,
    "text": "An electronics store orders 180 portable speakers at a cost of ₹420 each. The owner plans to price them so that selling only 140 speakers would guarantee a 30% profit on the total investment. However, a local event leads to the sale of 155 speakers. If the remaining speakers have no resale value, calculate the store's actual profit percentage on the total investment.",
    "options": { "A": "45.52%", "B": "46.83%", "C": "40.23%", "D": "43.92%" },
    "correct_answer_index": 3,
    "year": "2025"
  },
  {
    "question_number": 2,
    "text": "A seller bought three different types of mobile covers, M1, M2, and M3. The ratio of their selling prices was 3 : 4 : 5. He made a profit of 25% on M1, 10% on M2, but incurred a loss of 20% on M3. What was his approximate percent gain or loss in the entire transaction ?",
    "options": { "A": "profit of 3.3%", "B": "loss of 2.3%", "C": "loss of 2.6%", "D": "profit of 3.6%" },
    "correct_answer_index": 1,
    "year": "2025"
  },
  {
    "question_number": 3,
    "text": "A furniture establishment initially disposes of a particular dining chair for ₹X, thereby realising a 25% profit margin. Subsequently, as a promotional strategy for a festive period, the marked price of this identical chair is elevated to ₹1.8X. Following this adjustment, a special concession of 20% is applied to the newly established marked price. The inquiry then seeks to ascertain the resulting percentage profit generated by the store during this specific celebratory sales period. What is the percentage profit earned by the store during the festive sale ?",
    "options": { "A": "40%", "B": "80%", "C": "42%", "D": "70%" },
    "correct_answer_index": 1,
    "year": "2025"
  },
  {
    "question_number": 4,
    "text": "A bookseller sells 12 pens for ₹240, but in doing so, he incurs a loss equal to the cost price of 6 pens. The loss percent is:",
    "options": { "A": "40%", "B": "70%", "C": "60%", "D": "50%" },
    "correct_answer_index": 3,
    "year": "2025"
  },
  {
    "question_number": 5,
    "text": "Two types of sugar, one costing ₹35/kg and another costing ₹50/kg, are mixed with a third variety in the ratio 1 : 2 : 3. If the mixture is worth ₹44/kg, what is the price of the third variety of sugar per kg ?",
    "options": { "A": "₹43.00", "B": "₹42.50", "C": "₹44.00", "D": "₹55.50" },
    "correct_answer_index": 0,
    "year": "2025"
  },
  {
    "question_number": 6,
    "text": "A candy shop owner buys three kinds of candies: red, yellow , and green. Red candies are purchased at 3 for ₹15, yellow candies at 4 for ₹18, and green candies at 5 for ₹22. He mixes them in the ratio 1 : 1 : 2. He sells all the mixed candies at 3 for ₹20. What is his approximate gain or loss percentage ?",
    "options": { "A": "Loss of 45.21%", "B": "Profit of 45.71%", "C": "Profit of 55.71 %", "D": "Loss of 40.51 %" },
    "correct_answer_index": 1,
    "year": "2025"
  },
  {
    "question_number": 7,
    "text": "A milkman bought 50 liters of milk for ₹1000 . 5 liters of milk spoiled. At what rate per liter should he sell the remaining milk to make a profit of 25 % on his total outlay ?",
    "options": { "A": "₹27.78 per liter", "B": "₹26.24 per liter", "C": "₹27.36 per liter", "D": "₹26.82 per liter" },
    "correct_answer_index": 0,
    "year": "2025"
  },
  {
    "question_number": 8,
    "text": "A trader marks his goods 50% above the cost price and allows a discount of 20%. Find the profit or loss percent.",
    "options": { "A": "25% profit", "B": "20% profit", "C": "25% loss", "D": "20% loss" },
    "correct_answer_index": 1,
    "year": "2025"
  },
  {
    "question_number": 9,
    "text": "A shopkeeper buys an article for ₹900. He marks up its price by 10%. He then offers a discount of 20% on the marked price to a customer. What is the profit / loss percentage the shopkeeper makes on this transaction?",
    "options": { "A": "22%", "B": "18%", "C": "12%", "D": "10%" },
    "correct_answer_index": 2,
    "year": "2025"
  },
  {
    "question_number": 10,
    text: "A retailer bought a dozen shirts for ₹4800. He sold each shirt at ₹450. What is his total profit or loss percentage?",
    "options": { "A": "12.5% profit", "B": "15% profit", "C": "10% loss", "D": "20% profit" },
    "correct_answer_index": 0,
    "year": "2025"
  },
  {
    "question_number": 11,
    text: "A refrigerator manufacturer earns a profit of 15% by selling each refrigerator for Rs. 17,250. If the cost of production increases by 18%, then What should be the selling price of the refrigerator to earn a profit of 18% ?",
    "options": { "A": "₹ 20,886", "B": "₹ 34,086", "C": "₹ 19,094", "D": "₹ 21,032" },
    "correct_answer_index": 0,
    "year": null
  },
  {
    "question_number": 12,
    text: "A shopkeeper has a fault of 100 g in a 3 kg weight. He sold 3 kg of potatoes to Charu using the same faulty weight for ₹46. The cost price of the potatoes for the seller was ₹12 per kg. How much profit (in₹) did he earn on the potatoes ?",
    "options": { "A": "11.6", "B": "10.2", "C": "11.2", "D": "10" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 13,
    text: "If books bought at prices ranging from ₹200 to ₹260 are sold at prices ranging from ₹250 to 300, what is the greatest possible profit that might be made in selling 25 books?",
    "options": { "A": "₹2,300", "B": "₹2,500", "C": "₹1,800", "D": "₹2,700" },
    "correct_answer_index": 1,
    "year": null
  },
  {
    "question_number": 14,
    text: "A vendor started selling vegetables at ₹10 per kg, but couldn’t find buyers at this rate. So he reduced the price to ₹7.2 per kg, but uses a faulty weight of 900 g instead of 1 kg. Find the percentage change in the actual price.",
    "options": { "A": "10%", "B": "15%", "C": "20%", "D": "25%" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 15,
    text: "A seller sold 19 cookies for ₹95 instead of 20 cookies in one kg, cheating a customer. What is the gain (in ₹) if the seller bought the cookies for ₹76?",
    "options": { "A": "28.2", "B": "26.2", "C": "22.8", "D": "25.8" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 16,
    text: "If a shopkeeper sells sugar at ₹44.8 per kg, he is able to make a 12% profit. Due to water seepage, 1/5 of the sugar is damaged. What should now be the selling price per kg of the rest of the sugar to have a 5% profit?",
    "options": { "A": "₹49.5", "B": "₹52.5", "C": "₹48.5", "D": "₹51.8" },
    "correct_answer_index": 1,
    "year": null
  },
  {
    "question_number": 17,
    text: "By selling 30 metres of cloth a shopkeeper makes a profit equivalent to the selling price of 10 metres of cloth. Find the selling price of 1 metre of cloth when the cost price of 1 metre of cloth is ₹480.",
    "options": { "A": "₹520", "B": "₹960", "C": "₹720", "D": "₹820" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 18,
    text: "A reduction of 7.5% in the cost price of a commodity enables a shopkeeper to purchase 15 kg more than what he previously purchased for a sum of ₹7,400. In order to make a profit of 32.5% on the pre-reduction cost price of the commodity, at what price (in ₹) per kg should the commodity be sold ?",
    "options": { "A": "54", "B": "53", "C": "52", "D": "51" },
    "correct_answer_index": 1,
    "year": null
  },
  {
    "question_number": 19,
    text: "Ramanna purchased raw materials for a certain price to manufacture a product. However, owing to shortage of labour, 22.5% of the raw materials could not be utilised and got wasted. 80% of the cost of raw materials used was added as the cost of manufacturing. If Ramanna could sell his product at a price to earn an overall profit of 20% after offering a discount of 20%, how many times of the total cost of the raw materials purchased was the marked price of the product ?",
    "options": { "A": "2.44 times", "B": "2.42 times", "C": "2.43 times", "D": "2.40 times" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 20,
    text: "During the lockdown, a state government gives 4.5 kg of rice to each person of a family at a cost price of ₹40 per kg. But the distributor uses false weight of 3.75 kg instead of 4.5 kg and distributes the rice. The accumulated rice was sold in the black market at double the price. He showed the government that he distributed 2700 kg of rice. When caught, he was made to pay a fine of 125% of what he earned in the black market. What was his fine amount?",
    "options": { "A": "₹45,000", "B": "₹54,000", "C": "₹28,000", "D": "₹36,000" },
    "correct_answer_index": 0,
    "year": null
  },
  {
    "question_number": 21,
    text: "A shopkeeper claims to sell 450 kg rice at a cost price of ₹40 per kg but uses a weight of 900 grams instead of a one kilogram weight. He makes a profit of ₹2,520 by selling the remaining rice in the black market. The ratio of the black-market price to the original price per kg of rice is:",
    "options": { "A": "7 : 5", "B": "10 : 7", "C": "9 : 4", "D": "4 : 3" },
    "correct_answer_index": 0,
    "year": null
  },
  {
    "question_number": 22,
    text: "A person bought bananas at 6 for ₹12 and sold them at 8 for ₹10. Find his gain or loss percentage ?",
    "options": { "A": "3.75% gain", "B": "37.5% loss", "C": "375% gain", "D": "0.375% loss" },
    "correct_answer_index": 1,
    "year": null
  },
  {
    "question_number": 23,
    text: "A sells a watch to B at a profit of 33% and B sells it to C at a loss of 20%. If C pays ₹532, then what was the cost price for A?",
    "options": { "A": "₹500", "B": "₹800", "C": "₹400", "D": "₹600" },
    "correct_answer_index": 0,
    "year": null
  },
  {
    "question_number": 24,
    text: "B purchased 15 kg apples at the rate of ₹180 per kg from a wholesaler who uses a weight of 950 grams for the kg weight. B sold all these apples at ₹180 per kg but used a weight of 750 grams for the kg weight. Find the percentage profit earned by B in the transaction (correct to 2 places of decimal).",
    "options": { "A": "22.55%", "B": "25.75%", "C": "33.33%", "D": "26.67%" },
    "correct_answer_index": 3,
    "year": null
  },
  {
    "question_number": 25,
    text: "Aditya sold article X at a profit of 23% and article Y at a loss of 13%. He earned a profit of ₹180 in the entire transaction. If article X costs ₹90 less than article Y, then what is the price of article Y (in ₹ )?",
    "options": { "A": "2,007", "B": "2,050", "C": "2,100", "D": "2,020" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 26,
    text: "A company buys raw materials for ₹10,000 and manufactures a product that costs an additional ₹5,000 in labour and overhead. The product is sold to a distributor for ₹25,000, who marks it up by 20% and sells it to a retailer. The retailer then marks it up by another 25% and sells it to the end customer. What is the overall percentage profit made by the company, distributor, and retailer combined ?",
    "options": { "A": "100%", "B": "150%", "C": "125%", "D": "135%" },
    "correct_answer_index": 1,
    "year": null
  },
  {
    "question_number": 27,
    text: "By selling a TV set for ₹16,800, a salesman gains a profit of 20%. If the production cost is increased by 20%, find the new selling price of the set so as to gain 20%.",
    "options": { "A": "₹18,160", "B": "₹18,480", "C": "₹20,160", "D": "₹20,480" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 28,
    text: "Arun brought 50 kg of rice at a discount of 15% on the marked price. For purchasing bulk quantity, he was given 5 kg of wheat (the marked price of which was 60% the marked price of rice) free of cost. Had the retailer sold both items at their marked price to his other customers, then approximately what would be the profit percentage that the shopkeeper could earn ?",
    "options": { "A": "24.7%", "B": "25.2%", "C": "22.8%", "D": "23.5%" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 29,
    text: "A fruit seller buys 480 bananas for ₹1,200. Some of these bananas are rotten and hence, they are thrown away. He sells the remaining bananas at ₹3.5 each and makes a profit of ₹396. What is the percentage of bananas thrown away?",
    "options": { "A": "6%", "B": "4.5 %", "C": "5 %", "D": "4 %" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 30,
    text: "A tailor buys lining clothes from a wholesale merchant and cheats him by using a measurement tape which is 5 cm longer than the normal tape. The tailor offers the customers at cost price while stitching different garments and uses measurements tape which is 5 cm shorter than the normal tape. The gain percent is:",
    "options": { "A": "15%", "B": "10 10/19%", "C": "10%", "D": "10 10/25%" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 31,
    text: "Rini has mixed two colours 'C1' and 'C2' in the ratio 2 : 3. If the rate of the colour 'C1' is ₹500 per unit and she is selling the mixture of the two colours at ₹650 per unit at breakeven price, then what is the rate (in ₹) per unit of the second colour, that is, 'C2'?",
    "options": { "A": "750", "B": "725", "C": "760", "D": "765" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 32,
    text: "A shopkeeper purchased 1600 mangos at the rate of ₹120 per dozen. Out of these, he sold 900 mangoes at ₹15 per mango and the remaining mangoes at ₹14 per mango. His gain percentage is:",
    "options": { "A": "45.625%", "B": "38.265%", "C": "35.625%", "D": "48.765%" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 33,
    text: "A shopkeeper bought a certain number of apples for Rs.3,600. He sold one-fifth of them at a loss of 10%, one-fourth of the remaining apples at a loss of 5%, and two-third of the rest at a profit of 15%. At what price (in Rs.) should he sell the remaining apples to earn a profit of 27% overall?",
    "options": { "A": "1,548", "B": "1,584", "C": "1,845", "D": "1,864" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 34,
    text: "A retailer announces a discount of 30% for selling an air-conditioner marked at ₹92,000. The cost price of the air-conditioner is 70% below the marked price. He offers a further discount of 20% if the buyer presents his membership card of the retailer's store. The profit of the retailer with the membership card scheme is what percentage of the profit of the retailer without the membership card scheme?",
    "options": { "A": "62%", "B": "65%", "C": "70%", "D": "74%" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 35,
    text: "A shopkeeper is incurring a loss of cost price of 4 pens while selling 20 pens to Ajay. If the shopkeeper had purchased 20 pens at 10% less price and had sold 20 pens to Ajay at 25% more than the selling price, then how much percentage would he have gained (rounded off to 1 decimal place)?",
    "options": { "A": "8.0", "B": "11.1", "C": "10.0", "D": "12.5" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 36,
    text: "Ten refrigerators and four mobile phones together cost ₹2,10,000 while six refrigerators and two mobile phones together cost ₹1,22,000. The cost (in ₹) of one refrigerator and two mobile phones is:",
    "options": { "A": "37000", "B": "35200", "C": "34500", "D": "36000" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 37,
    text: "Mukesh sells two shirts. The cost price of the first shirt is equal to the selling price of the second shirt. The first shirt is sold at a profit of 20% and the second shirt is sold at a loss of 20%. What is the ratio of the selling price of the first shirt to the cost price of the second shirt?",
    "options": { "A": "18 : 25", "B": "97 : 100", "C": "24 : 25", "D": "27 : 50" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 38,
    text: "Kapil bought 100 frocks at the rate of ₹320 per frock. Transport expenditure was ₹1000. He paid a tax of ₹1.50 per frock and the labor fee was ₹500. What should be the selling price per frock if she wants to make a profit of 10%?",
    "options": { "A": "₹385.45", "B": "₹370.15", "C": "₹390.80", "D": "₹336.50" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 39,
    text: "Akshay has 30 articles, each having the same cost price. He marked the price of each article at 30% above its cost price. He sold 15 of the articles at a discount of 20% each and the remaining 15 articles at a discount of 10% each, thereby gaining a total profit of ₹630. What was the cost price of each article?",
    "options": { "A": "₹ 240", "B": "₹ 180", "C": "₹ 280", "D": "₹ 200" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 40,
    text: "A dishonest dealer is selling sugar at Rs. 40 per kg and pretending that he is selling it at a loss of Rs. 5 per kg but he actually gives 800g instead of 1 kg, using a faulty weight. What is his actual profit or loss percent?",
    "options": { "A": "Gain, 11%", "B": "Gain, 11 1/9%", "C": "Loss. 10 1/9%", "D": "Loss, 9 1/9%" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 41,
    text: "A woman sold her earphone for Rs. 2,000 and got a percentage profit equal to the numerical value of cost price. The cost price of the earphone is:",
    "options": { "A": "Rs. 500", "B": "Rs. 200", "C": "Rs. 600", "D": "Rs. 400" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 42,
    text: "A manufacturer sells an item to a wholesale dealer at a profit of 11%. The wholesaler sells the same to a retailer at a profit of 15%. The retailer in turn sells it to a customer for ₹17,045, thereby earning a profit of 19%. The cost price of the manufacturer is (consider integral part only) :",
    "options": { "A": "₹13,520", "B": "₹15,020", "C": "₹10,200", "D": "₹11,220" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 43,
    text: "Aditya sells two wrist watches from his personal collection for ₹12,600 each. On the first watch he gains 26% and on the second he loses 10%. Find the overall loss or profit percentage?",
    "options": { "A": "Gain of 16%", "B": "Gain of 5%", "C": "Loss of 5%", "D": "Gain of 12%" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 44,
    text: "Sushant buys goods worth Rs.8000. He gets a discount of 10% on that article. After getting the exemption, he pays tax at the rate of 7.5%. Find the amount he will have to pay for this goods received at his residence, if the shopkeeper charges Rs.200 for home delivery.",
    "options": { "A": "Rs.7940", "B": "Rs.8155", "C": "Rs.9660", "D": "Rs.6851" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 45,
    text: "The difference between the selling prices of some apples, if sold for ₹12 per apple instead of ₹9 per apple, is ₹870. If total cost price of all the apples is ₹2,320, then find the selling price of one apple if the profit earned is 25%",
    "options": { "A": "₹15", "B": "₹10", "C": "₹12", "D": "₹8" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 46,
    text: "Joseph bought two woollen jackets for Rs. 2100 and Rs. 3150 respectively. By selling the first at a gain of k% and the second at a loss of k%, he found the selling price of both is the same. What is the value of k?",
    "options": { "A": "20", "B": "22.64", "C": "15", "D": "25" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 47,
    text: "When an article is sold for Rs.720, there is a profit of x%. When the same article is sold for Rs.750, profit is (x + 5) %. What is the value of x ?",
    "options": { "A": "20", "B": "18", "C": "25", "D": "1" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 48,
    text: "35% of goods were sold at a profit of 65%, while the remaining were sold at x% loss. If the overall loss is 12%, then what is the value of x? (correct to one decimal place)",
    "options": { "A": "51.8", "B": "50.6", "C": "53.5", "D": "52.4" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 49,
    text: "How many kg of salt costing Rs. 28 per kg must be mixed with 6.6 kg of salt costing Rs. 16 per kg, so that selling the mixture at Rs. 29.90, there is a gain of 15%?",
    "options": { "A": "33", "B": "31", "C": "35", "D": "32" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 50,
    text: "By selling two articles for Rs 800, a person gains the cost price of three articles. The profit percent is:",
    "options": { "A": "125", "B": "140", "C": "120", "D": "150" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 51,
    text: "An article is sold at a certain price. If it is sold at 33 1/3 % of this price, there is a loss of 33 1/3 %. What is the percentage profit when it is sold at 60% of the original selling price?",
    "options": { "A": "20", "B": "30", "C": "33 1/3", "D": "17 1/3" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 52,
    text: "Sujata sold 25 articles for Rs. 1250 and she incurred a loss of 10%. How many articles should she sell for Rs. 2600 so that she can get a profit of 17% ?",
    "options": { "A": "26", "B": "40", "C": "25", "D": "42" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 53,
    text: "The sum of cost prices of A and B is Rs. 1200. The sum of the selling prices of A and B is Rs. 1390. If the profit of 10% and 20% is obtained on A and B respectively, then find the ratio between the cost prices of A and B.",
    "options": { "A": "5 : 7", "B": "5 : 9", "C": "7 : 13", "D": "6 : 11" },
    "correct_answer_index": 0,
    year: null
  },
  {
    question_number: 54,
    text: "A shopkeeper earns the same percent of profit as well as loss by selling two similar pieces of furniture for Rs 18000 and Rs 10000, respectively. At what price should he sell it to earn a profit of 50%?",
    "options": { "A": "Rs 21,000", "B": "Rs 20,250", "C": "Rs 21,750", "D": "Rs 19,500" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 55,
    text: "A shopkeeper gains 400% on a transaction. If the cost increases by 100% and there is no change in the selling price, then find the ratio between new profit and selling price.",
    "options": { "A": "1 : 3", "B": "2 : 5", "C": "3 : 5", "D": "1 : 2" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 56,
    text: "Parikh sold his pen at a profit of Rs 11. He calculated the profit percentage on selling price and found it to be 25%. the cost price (in Rs) of the pen is:",
    "options": { "A": "33", "B": "24", "C": "36", "D": "44" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 57,
    text: "If 20% of the goods are sold at 50% profit, 40% of the goods at 20% loss, 20% of the goods at 5% loss and the remaining at no loss or no profit, then the overall profit percentage is:",
    "options": { "A": "5%", "B": "8%", "C": "4%", "D": "1%" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 58,
    text: "Two articles were sold for Rs 2400 each by a shopkeeper. The shopkeeper incurred no profit and no loss on the whole transaction. If one of the two articles sold at a profit of 20%, then what was the loss incurred on the other article?",
    "options": { "A": "600", "B": "400", "C": "380", "D": "240" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 59,
    text: "P sold an article to Q at a profit of 20%. Q sold the same article to R at a loss of 25%. R sold the same article to T at a profit of 50%. If P bought the article at Rs 100, then at what price did T buy that article?",
    "options": { "A": "145", "B": "125", "C": "115", "D": "135" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 60,
    text: "A sold an article on 15% profit for Rs. 1495. He purchased another article whose cost price was equal to that of the first article. He sold this new article at 10% profit. What is the total profit of A ?",
    "options": { "A": "325", "B": "450", "C": "375", "D": "425" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 61,
    text: "The cost prices of article A and article B are Rs. 1200 and Rs. 1600 respectively. The selling price of article A is Rs. 1380 and the total profit after selling both the articles is 25%. What is the profit percentage on the article B ?",
    "options": { "A": "27.5", "B": "32.5", "C": "29.5", "D": "35.5" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 62,
    text: "An article is sold for Rs 6500 so as to earn a profit of 4%. A second article whose cost price is Rs 3750, is sold at a loss of 4%. What is the overall gain or loss percent in the whole transaction?",
    "options": { "A": "Gain 45%", "B": "Loss 1%", "C": "Loss 4%", "D": "Gain 1%" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 63,
    text: "A man bought three articles for Rs 3,000 each. He sold the articles respectively at 10% profit, 5% profit and 15% loss. The total percentage profit/loss he earned is:",
    "options": { "A": "10% loss", "B": "5% loss", "C": "5% profit", "D": "No profit no loss" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 64,
    text: "A person sells an article at a profit of 12%. If he had purchased it for 12% less and sold it for Rs.9 less, he would have gained 27%. What is the original cost price of the article?",
    "options": { "A": "4,250", "B": "4,000", "C": "4,500", "D": "3,750" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 65,
    text: "Sushma bought 6 tables and 12 chairs for Rs.12000. She sold the tables at a profit of 15% and the chairs at a loss of 10%. If her total gain was 300, then the total cost of the tables was:",
    "options": { "A": "6000", "B": "5000", "C": "5400", "D": "4800" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 66,
    text: "Abhi bought two articles for Rs.624. He sold one at a loss of 14% and the other at a profit of 14%. If the selling price of both the articles is equal, then the difference between their cost prices (in Rs) is:",
    "options": { "A": "89.64", "B": "87.36", "C": "89.68", "D": "88.84" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 67,
    text: "The marked price of an article is Rs. 315. It is sold for Rs. 288. If there is a loss of 4%, then by what percent above the cost is the article marked?",
    "options": { "A": "5%", "B": "8%", "C": "6%", "D": "5 1/2%" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 68,
    text: "A person sold an article at a loss of 15%. Had he sold it for Rs. 30.60 more, he would have gained 9%. To gain 10%, he should have sold it for:",
    "options": { "A": "Rs. 140.25", "B": "Rs. 132", "C": "Rs. 130", "D": "Rs. 128.40" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 69,
    text: "A bought 38 kg. Rice at Rs. 54.50/kg, 45 Kg rice at Rs. 62/kg, and 55 kg rice at Rs. 48/kg . He sold the mixture at Rs. 65/kg. His loss or profit percentage is:",
    "options": { "A": "Loss 1.04", "B": "Loss 1.7", "C": "Profit 19.6", "D": "Profit 16.8" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 70,
    text: "Three partners A, B and C share profit and losses in the ratio 3 : 4 : 7 If the profit for the year before charging 30% tax is Rs. 1,10,166 What is B’s share of profit after tax?",
    "options": { "A": "Rs.9442.80", "B": "Rs.31476", "C": "Rs.22033.20", "D": "Rs.24673.10" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 71,
    text: "A cyclist sells 3 cycles at the loss of Rs. 129 per bicycle and 12 cycles on the profit of 516 per cycle. If the total profit on all the bicycles sold is 15%, then what will be the cost per cycle?",
    "options": { "A": "2960", "B": "3870", "C": "2580", "D": "4440" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 72,
    text: "A manufacturer sells the product to a wholesaler at 6% profit, the wholesaler sells the product to a retailer at 8% profit and the retailer sells the product to his customer at 10% profit. The price paid by the customer is Rs 31,482. The cost of the product to the manufacturer is:",
    "options": { "A": "28,306", "B": "26,524", "C": "25,000", "D": "26,980" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 73,
    text: "Kusum purchased 22 liters of milk at ₹42 per liter and another 15 liters of milk at ₹50 per liter. She combined both quantities and then sold the entire mixture at ₹48 per liter. What was her total profit or loss ?",
    "options": { "A": "Loss of ₹102", "B": "Profit of ₹102", "C": "Profit of ₹51", "D": "Loss of ₹51" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 74,
    text: "A fruit seller sells apples at a loss of 10 % on the cost price but uses a weight that is 25% less than the actual weight. Find his total profit percentage.",
    "options": { "A": "16.626%", "B": "16.257%", "C": "20%", "D": "18.757%" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 75,
    text: "The profit made on an item sold for ₹2200 is equal to the loss incurred when it is sold for ₹1800. What will be the profit or loss percentage if the item is sold for ₹2150 ?",
    "options": { "A": "Profit of 7.25%", "B": "Loss of 5.5%", "C": "Profit of 7.5%", "D": "Loss of 5.25%" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 76,
    text: "A Shopkeeper sold 15 lunch boxes for ₹3000 and gained a profit of 25%. How many lunch boxes should he sell for ₹2816 to make a profit of 10% ?",
    "options": { "A": "14", "B": "16", "C": "20", "D": "19" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 77,
    text: "A trader sells one brand of coffee at ₹150 per kg, incurring a 25% loss. He also sells another brand of coffee at ₹200 per kg, incurring a 20% loss. If he mixes the two brands in equal proportions and sells the mixture at ₹175 per kg, what is his overall profit or loss percentage ?",
    "options": { "A": "Loss of 22.22%", "B": "Profit of 20.20%", "C": "Loss of 20.20%", "D": "Profit of 22.22%" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 78,
    text: "A tea seller bought 20 kg of Darjeeling tea at ₹310 per kg and 15 kg of Assam tea at ₹220 per kg. He mixed them together. Due to a slight drop in market prices, he had to sell the entire mixture at ₹260 per kg. Calculate his total profit or loss.",
    "options": { "A": "Loss of ₹400", "B": "Profit of ₹400", "C": "Loss of ₹200", "D": "Profit of ₹200" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 79,
    text: "A car dealer sold three cars, A, B, and C, whose selling prices were in the ratio 5 : 4 : 6. He made a profit of 50% on car A, a loss of 10% on car B, and an equal loss (no profit or loss) on car C. What was his approximate profit or loss percentage on the total transaction ?",
    "options": { "A": "loss of 8.88%", "B": "profit of 8.88%", "C": "profit of 10.88%", "D": "loss of 10.88%" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 80,
    text: "Three varieties of lentils, priced at ₹50/kg, ₹40/kg, and a third at an unknown price, are mixed in the ratio 3 : 2 : 5. If the resulting mixture is sold at ₹55/kg, making a profit of 10% on the cost price, what is the price per kg of the third variety of lentils ?",
    "options": { "A": "₹53.50", "B": "₹55.50", "C": "₹54.00", "D": "₹62.50" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 81,
    text: "A vendor mixes two types of rice – one costing ₹110 per kg and the other costing ₹170 per kg, in the ratio 2 : 3. If he sells the mixed variety at ₹142 per kg, find his gain or loss percent.",
    "options": { "A": "2.74% loss", "B": "2.74% gain", "C": "3.25% Loss", "D": "3.25% Gain" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 82,
    text: "A shopkeeper made a loss of ₹135 on an article. If the loss percentage was 10%, what was the cost price of the article (in ₹)?",
    "options": { "A": "₹1347", "B": "₹1345", "C": "₹1350", "D": "₹1400" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 83,
    text: "Two varieties of rice are sold at ₹72 per kg and ₹60 per kg respectively, with profit percentages of 20% and 25%. When they are mixed in the ratio 2 : 1 and sold at ₹70 per kg, calculate the net percentage gain or loss.",
    "options": { "A": "Profit of 50%", "B": "Loss of 25%", "C": "Profit of 25%", "D": "Loss of 50%" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 84,
    text: "A clothing store sold three dresses, D1, D2, and D3, whose selling prices were in the ratio 12 : 6 : 3 . They made a profit of 20% on D1, a loss of 10% on D2, and a profit of 5% on D3. What was their approximate total profit or loss percentage for the entire sale ?",
    "options": { "A": "profit of 7.58%", "B": "loss of 10.78%", "C": "profit of 10.78%", "D": "loss of 7.58%" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 85,
    text: "A shopkeeper mixes 50 kg of sugar costing ₹60 per kg with a certain quantity of sugar costing ₹90 per kg. If he sells the mixture at ₹84 per kg and makes a 20% profit, find the quantity of the second type of sugar that was mixed.",
    "options": { "A": "30 kg", "B": "25 kg", "C": "20 kg", "D": "15 kg" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 86,
    text: "A fruit seller buys three varieties of mangoes. The first variety is bought at 8 for ₹20, the second at 10 for ₹24, and the third at 4 for ₹10. He mixes them in the ratio 2 : 3 : 1 respectively. If he sells all the mangoes at 6 for ₹14, what is his approximate gain or loss percentage ?",
    "options": { "A": "Profit of 4.76%", "B": "Loss of 4.76%", "C": "Loss of 6%", "D": "Profit of 6%" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 87,
    text: "A flower vendor bought 300 flowers for ₹900. 90 flowers withered and became unsellable. At what price per flower should he sell the remaining flowers to earn a profit of 40% on his total cost ?",
    "options": { "A": "₹7", "B": "₹6", "C": "₹5", "D": "₹3" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 88,
    text: "The ratio of the profit to the cost price of a product is 3 : 8. What is the ratio of its selling price to its profit ?",
    "options": { "A": "7 : 2", "B": "11 : 10", "C": "5 : 15", "D": "11 : 3" },
    "correct_answer_index": 3,
    year: "2025"
  },
  {
    "question_number": 89,
    text: "A shop sells a shirt for ₹ P , incurring a loss of 10%. They mark it up to ₹1.8P and then provide a 20% discount. What is the percentage profit or loss ?",
    "options": { "A": "24.6% Profit", "B": "28.6% Loss", "C": "29.6% Profit", "D": "34.6% Loss" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 90,
    text: "A shopkeeper mixes two types of pulses costing ₹80/kg and ₹100/kg. He sells the mixture at ₹112.5/kg, earning a 25% profit. In what ratio did he mix the two types of pulses ?",
    "options": { "A": "1 : 3", "B": "1 : 1", "C": "3 : 2", "D": "4 : 1" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 91,
    text: "A stationery shop owner buys three types of pencils. The first type costs him 10 pencils for ₹20, the second 3 pencils for ₹9, and the third 9 pencils for ₹45. He mixes them in the ratio 3 : 4 : 3. If he sells all the pencils at 4 for ₹21, what is his approximate gain or loss percentage ?",
    "options": { "A": "Loss of 59.09%", "B": "Profit of 59.09%", "C": "Profit of 60%", "D": "Loss of 60%" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 92,
    text: "A shopkeeper mixes two qualities of Rice. The first quality costs ₹150 per kg and is mixed with the second quality in the ratio 4 : 5. If the mixture is sold at ₹130 per kg (at no profit, no loss), what is the cost per kg of the second quality of Rice ?",
    "options": { "A": "₹100", "B": "₹110", "C": "₹114", "D": "₹120" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 93,
    text: "A grocer purchased 40 kg of rice at ₹40 per kg and 30 kg of another variety of rice at ₹55 per kg. He mixed the two varieties and sold the entire mixture at ₹48 per kg. Find his total profit or loss in this transaction.",
    "options": { "A": "Loss of ₹110", "B": "Loss of ₹240", "C": "Profit of ₹110", "D": "Loss of ₹290" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 94,
    text: "A Smart watch retailer sells a Smart watch for ₹P and earns a profit of 20%. For a special festive offer, he marks the same Smart watch at ₹1.5P . At the offer, he provides a discount of 10%. What will be the percentage profit that he will make during the festive offer?",
    "options": { "A": "36%", "B": "46%", "C": "62%", "D": "60%" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 95,
    text: "If the ratio between the loss and cost price of an article is 1 : 5, then the ratio between its selling price and cost price is_______.",
    "options": { "A": "9 : 10", "B": "4 : 5", "C": "2 : 5", "D": "7 : 10" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 96,
    text: "A shopkeeper mixes two varieties of pulses - one costing ₹50 per kg and the other costing ₹90 per kg, in the ratio 3 : 1. If he sells the mixed variety at ₹96 per kg, find his gain or loss percent.",
    "options": { "A": "60% Gain", "B": "40% Gain", "C": "45% Loss", "D": "60% Loss" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 97,
    text: "A fruit vendor sells 20 kg of oranges for ₹900, thereby gaining the cost price of 5 kg of oranges. What is his profit percentage ?",
    "options": { "A": "28.65%", "B": "25%", "C": "26%", "D": "31.56%" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 98,
    text: "The cost price of an article is ₹200. A shopkeeper sells it at a discount of 20% on the marked price. If the marked price is ₹400, what is the shopkeeper's profit or loss percentage ?",
    "options": { "A": "60% Profit", "B": "60% Loss", "C": "30% Profit", "D": "30% Loss" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 99,
    text: "A grocer mixes two varieties of rice one costing ₹40 per kg and the other costing ₹50 per kg, in the ratio 3 : 5. If he sells the mixed variety at ₹55.50 per kg, find his gain or loss percent.",
    "options": { "A": "20% Loss", "B": "20% Gain", "C": "18% Gain", "D": "18% Loss" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 100,
    text: "A can contains 30 litres of oil at Rs. 40/litre. Another can contains 70 litres of oil at Rs. 50/litre. They are mixed, and 25 litres are sold at Rs. 60/litre. How much profit or loss does the seller make on this sale ?",
    "options": { "A": "Rs. 600 profit", "B": "Rs. 325 loss", "C": "Rs. 280 loss", "D": "Rs. 325 profit" },
    "correct_answer_index": 3,
    year: "2025"
  }
  ],
});