window.BASE_CHAPTERS = window.BASE_CHAPTERS || [];
window.BASE_CHAPTERS.push({
  id: "Profit-Loss",
  title: "Profit and Loss",
  desc: "SSC CGL PYQs focused on Profit and Loss.",
  questions: [
  {
    "question_number": 1,
    "text": "An electronics store orders 180 portable speakers at a cost of ₹420 each. The owner plans to price them so that selling only 140 speakers would guarantee a 30% profit on the total investment. However, a local event leads to the sale of 155 speakers. If the remaining speakers have no resale value, calculate the store's actual profit percentage on the total investment.",
    "options": { "A": "45.52%", "B": "46.83%", "C": "40.23%", "D": "43.92%" },
    "correct_answer_index": 3,
    "year": "2025"
  },
  {
    "question_number": 2,
    "text": "A seller bought three different types of mobile covers, M1, M2, and M3. The ratio of their selling prices was 3 : 4 : 5. He made a profit of 25% on M1, 10% on M2, but incurred a loss of 20% on M3. What was his approximate percent gain or loss in the entire transaction ?",
    "options": { "A": "profit of 3.3%", "B": "loss of 2.3%", "C": "loss of 2.6%", "D": "profit of 3.6%" },
    "correct_answer_index": 1,
    "year": "2025"
  },
  {
    "question_number": 3,
    "text": "A furniture establishment initially disposes of a particular dining chair for ₹X, thereby realising a 25% profit margin. Subsequently, as a promotional strategy for a festive period, the marked price of this identical chair is elevated to ₹1.8X. Following this adjustment, a special concession of 20% is applied to the newly established marked price. The inquiry then seeks to ascertain the resulting percentage profit generated by the store during this specific celebratory sales period. What is the percentage profit earned by the store during the festive sale ?",
    "options": { "A": "40%", "B": "80%", "C": "42%", "D": "70%" },
    "correct_answer_index": 1,
    "year": "2025"
  },
  {
    "question_number": 4,
    "text": "A bookseller sells 12 pens for ₹240, but in doing so, he incurs a loss equal to the cost price of 6 pens. The loss percent is:",
    "options": { "A": "40%", "B": "70%", "C": "60%", "D": "50%" },
    "correct_answer_index": 3,
    "year": "2025"
  },
  {
    "question_number": 5,
    "text": "Two types of sugar, one costing ₹35/kg and another costing ₹50/kg, are mixed with a third variety in the ratio 1 : 2 : 3. If the mixture is worth ₹44/kg, what is the price of the third variety of sugar per kg ?",
    "options": { "A": "₹43.00", "B": "₹42.50", "C": "₹44.00", "D": "₹55.50" },
    "correct_answer_index": 0,
    "year": "2025"
  },
  {
    "question_number": 6,
    "text": "A candy shop owner buys three kinds of candies: red, yellow , and green. Red candies are purchased at 3 for ₹15, yellow candies at 4 for ₹18, and green candies at 5 for ₹22. He mixes them in the ratio 1 : 1 : 2. He sells all the mixed candies at 3 for ₹20. What is his approximate gain or loss percentage ?",
    "options": { "A": "Loss of 45.21%", "B": "Profit of 45.71%", "C": "Profit of 55.71 %", "D": "Loss of 40.51 %" },
    "correct_answer_index": 1,
    "year": "2025"
  },
  {
    "question_number": 7,
    "text": "A milkman bought 50 liters of milk for ₹1000 . 5 liters of milk spoiled. At what rate per liter should he sell the remaining milk to make a profit of 25 % on his total outlay ?",
    "options": { "A": "₹27.78 per liter", "B": "₹26.24 per liter", "C": "₹27.36 per liter", "D": "₹26.82 per liter" },
    "correct_answer_index": 0,
    "year": "2025"
  },
  {
    "question_number": 8,
    "text": "A trader marks his goods 50% above the cost price and allows a discount of 20%. Find the profit or loss percent.",
    "options": { "A": "25% profit", "B": "20% profit", "C": "25% loss", "D": "20% loss" },
    "correct_answer_index": 1,
    "year": "2025"
  },
  {
    "question_number": 9,
    "text": "A shopkeeper buys an article for ₹900. He marks up its price by 10%. He then offers a discount of 20% on the marked price to a customer. What is the profit / loss percentage the shopkeeper makes on this transaction?",
    "options": { "A": "22%", "B": "18%", "C": "12%", "D": "10%" },
    "correct_answer_index": 2,
    "year": "2025"
  },
  {
    "question_number": 10,
    text: "A retailer bought a dozen shirts for ₹4800. He sold each shirt at ₹450. What is his total profit or loss percentage?",
    "options": { "A": "12.5% profit", "B": "15% profit", "C": "10% loss", "D": "20% profit" },
    "correct_answer_index": 0,
    "year": "2025"
  },
  {
    "question_number": 11,
    text: "A refrigerator manufacturer earns a profit of 15% by selling each refrigerator for Rs. 17,250. If the cost of production increases by 18%, then What should be the selling price of the refrigerator to earn a profit of 18% ?",
    "options": { "A": "₹ 20,886", "B": "₹ 34,086", "C": "₹ 19,094", "D": "₹ 21,032" },
    "correct_answer_index": 0,
    "year": null
  },
  {
    "question_number": 12,
    text: "A shopkeeper has a fault of 100 g in a 3 kg weight. He sold 3 kg of potatoes to Charu using the same faulty weight for ₹46. The cost price of the potatoes for the seller was ₹12 per kg. How much profit (in₹) did he earn on the potatoes ?",
    "options": { "A": "11.6", "B": "10.2", "C": "11.2", "D": "10" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 13,
    text: "If books bought at prices ranging from ₹200 to ₹260 are sold at prices ranging from ₹250 to 300, what is the greatest possible profit that might be made in selling 25 books?",
    "options": { "A": "₹2,300", "B": "₹2,500", "C": "₹1,800", "D": "₹2,700" },
    "correct_answer_index": 1,
    "year": null
  },
  {
    "question_number": 14,
    text: "A vendor started selling vegetables at ₹10 per kg, but couldn’t find buyers at this rate. So he reduced the price to ₹7.2 per kg, but uses a faulty weight of 900 g instead of 1 kg. Find the percentage change in the actual price.",
    "options": { "A": "10%", "B": "15%", "C": "20%", "D": "25%" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 15,
    text: "A seller sold 19 cookies for ₹95 instead of 20 cookies in one kg, cheating a customer. What is the gain (in ₹) if the seller bought the cookies for ₹76?",
    "options": { "A": "28.2", "B": "26.2", "C": "22.8", "D": "25.8" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 16,
    text: "If a shopkeeper sells sugar at ₹44.8 per kg, he is able to make a 12% profit. Due to water seepage, 1/5 of the sugar is damaged. What should now be the selling price per kg of the rest of the sugar to have a 5% profit?",
    "options": { "A": "₹49.5", "B": "₹52.5", "C": "₹48.5", "D": "₹51.8" },
    "correct_answer_index": 1,
    "year": null
  },
  {
    "question_number": 17,
    text: "By selling 30 metres of cloth a shopkeeper makes a profit equivalent to the selling price of 10 metres of cloth. Find the selling price of 1 metre of cloth when the cost price of 1 metre of cloth is ₹480.",
    "options": { "A": "₹520", "B": "₹960", "C": "₹720", "D": "₹820" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 18,
    text: "A reduction of 7.5% in the cost price of a commodity enables a shopkeeper to purchase 15 kg more than what he previously purchased for a sum of ₹7,400. In order to make a profit of 32.5% on the pre-reduction cost price of the commodity, at what price (in ₹) per kg should the commodity be sold ?",
    "options": { "A": "54", "B": "53", "C": "52", "D": "51" },
    "correct_answer_index": 1,
    "year": null
  },
  {
    "question_number": 19,
    text: "Ramanna purchased raw materials for a certain price to manufacture a product. However, owing to shortage of labour, 22.5% of the raw materials could not be utilised and got wasted. 80% of the cost of raw materials used was added as the cost of manufacturing. If Ramanna could sell his product at a price to earn an overall profit of 20% after offering a discount of 20%, how many times of the total cost of the raw materials purchased was the marked price of the product ?",
    "options": { "A": "2.44 times", "B": "2.42 times", "C": "2.43 times", "D": "2.40 times" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 20,
    text: "During the lockdown, a state government gives 4.5 kg of rice to each person of a family at a cost price of ₹40 per kg. But the distributor uses false weight of 3.75 kg instead of 4.5 kg and distributes the rice. The accumulated rice was sold in the black market at double the price. He showed the government that he distributed 2700 kg of rice. When caught, he was made to pay a fine of 125% of what he earned in the black market. What was his fine amount?",
    "options": { "A": "₹45,000", "B": "₹54,000", "C": "₹28,000", "D": "₹36,000" },
    "correct_answer_index": 0,
    "year": null
  },
  {
    "question_number": 21,
    text: "A shopkeeper claims to sell 450 kg rice at a cost price of ₹40 per kg but uses a weight of 900 grams instead of a one kilogram weight. He makes a profit of ₹2,520 by selling the remaining rice in the black market. The ratio of the black-market price to the original price per kg of rice is:",
    "options": { "A": "7 : 5", "B": "10 : 7", "C": "9 : 4", "D": "4 : 3" },
    "correct_answer_index": 0,
    "year": null
  },
  {
    "question_number": 22,
    text: "A person bought bananas at 6 for ₹12 and sold them at 8 for ₹10. Find his gain or loss percentage ?",
    "options": { "A": "3.75% gain", "B": "37.5% loss", "C": "375% gain", "D": "0.375% loss" },
    "correct_answer_index": 1,
    "year": null
  },
  {
    "question_number": 23,
    text: "A sells a watch to B at a profit of 33% and B sells it to C at a loss of 20%. If C pays ₹532, then what was the cost price for A?",
    "options": { "A": "₹500", "B": "₹800", "C": "₹400", "D": "₹600" },
    "correct_answer_index": 0,
    "year": null
  },
  {
    "question_number": 24,
    text: "B purchased 15 kg apples at the rate of ₹180 per kg from a wholesaler who uses a weight of 950 grams for the kg weight. B sold all these apples at ₹180 per kg but used a weight of 750 grams for the kg weight. Find the percentage profit earned by B in the transaction (correct to 2 places of decimal).",
    "options": { "A": "22.55%", "B": "25.75%", "C": "33.33%", "D": "26.67%" },
    "correct_answer_index": 3,
    "year": null
  },
  {
    "question_number": 25,
    text: "Aditya sold article X at a profit of 23% and article Y at a loss of 13%. He earned a profit of ₹180 in the entire transaction. If article X costs ₹90 less than article Y, then what is the price of article Y (in ₹ )?",
    "options": { "A": "2,007", "B": "2,050", "C": "2,100", "D": "2,020" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 26,
    text: "A company buys raw materials for ₹10,000 and manufactures a product that costs an additional ₹5,000 in labour and overhead. The product is sold to a distributor for ₹25,000, who marks it up by 20% and sells it to a retailer. The retailer then marks it up by another 25% and sells it to the end customer. What is the overall percentage profit made by the company, distributor, and retailer combined ?",
    "options": { "A": "100%", "B": "150%", "C": "125%", "D": "135%" },
    "correct_answer_index": 1,
    "year": null
  },
  {
    "question_number": 27,
    text: "By selling a TV set for ₹16,800, a salesman gains a profit of 20%. If the production cost is increased by 20%, find the new selling price of the set so as to gain 20%.",
    "options": { "A": "₹18,160", "B": "₹18,480", "C": "₹20,160", "D": "₹20,480" },
    "correct_answer_index": 2,
    "year": null
  },
  {
    "question_number": 28,
    text: "Arun brought 50 kg of rice at a discount of 15% on the marked price. For purchasing bulk quantity, he was given 5 kg of wheat (the marked price of which was 60% the marked price of rice) free of cost. Had the retailer sold both items at their marked price to his other customers, then approximately what would be the profit percentage that the shopkeeper could earn ?",
    "options": { "A": "24.7%", "B": "25.2%", "C": "22.8%", "D": "23.5%" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 29,
    text: "A fruit seller buys 480 bananas for ₹1,200. Some of these bananas are rotten and hence, they are thrown away. He sells the remaining bananas at ₹3.5 each and makes a profit of ₹396. What is the percentage of bananas thrown away?",
    "options": { "A": "6%", "B": "4.5 %", "C": "5 %", "D": "4 %" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 30,
    text: "A tailor buys lining clothes from a wholesale merchant and cheats him by using a measurement tape which is 5 cm longer than the normal tape. The tailor offers the customers at cost price while stitching different garments and uses measurements tape which is 5 cm shorter than the normal tape. The gain percent is:",
    "options": { "A": "15%", "B": "10 10/19%", "C": "10%", "D": "10 10/25%" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 31,
    text: "Rini has mixed two colours 'C1' and 'C2' in the ratio 2 : 3. If the rate of the colour 'C1' is ₹500 per unit and she is selling the mixture of the two colours at ₹650 per unit at breakeven price, then what is the rate (in ₹) per unit of the second colour, that is, 'C2'?",
    "options": { "A": "750", "B": "725", "C": "760", "D": "765" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 32,
    text: "A shopkeeper purchased 1600 mangos at the rate of ₹120 per dozen. Out of these, he sold 900 mangoes at ₹15 per mango and the remaining mangoes at ₹14 per mango. His gain percentage is:",
    "options": { "A": "45.625%", "B": "38.265%", "C": "35.625%", "D": "48.765%" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 33,
    text: "A shopkeeper bought a certain number of apples for Rs.3,600. He sold one-fifth of them at a loss of 10%, one-fourth of the remaining apples at a loss of 5%, and two-third of the rest at a profit of 15%. At what price (in Rs.) should he sell the remaining apples to earn a profit of 27% overall?",
    "options": { "A": "1,548", "B": "1,584", "C": "1,845", "D": "1,864" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 34,
    text: "A retailer announces a discount of 30% for selling an air-conditioner marked at ₹92,000. The cost price of the air-conditioner is 70% below the marked price. He offers a further discount of 20% if the buyer presents his membership card of the retailer's store. The profit of the retailer with the membership card scheme is what percentage of the profit of the retailer without the membership card scheme?",
    "options": { "A": "62%", "B": "65%", "C": "70%", "D": "74%" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 35,
    text: "A shopkeeper is incurring a loss of cost price of 4 pens while selling 20 pens to Ajay. If the shopkeeper had purchased 20 pens at 10% less price and had sold 20 pens to Ajay at 25% more than the selling price, then how much percentage would he have gained (rounded off to 1 decimal place)?",
    "options": { "A": "8.0", "B": "11.1", "C": "10.0", "D": "12.5" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 36,
    text: "Ten refrigerators and four mobile phones together cost ₹2,10,000 while six refrigerators and two mobile phones together cost ₹1,22,000. The cost (in ₹) of one refrigerator and two mobile phones is:",
    "options": { "A": "37000", "B": "35200", "C": "34500", "D": "36000" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 37,
    text: "Mukesh sells two shirts. The cost price of the first shirt is equal to the selling price of the second shirt. The first shirt is sold at a profit of 20% and the second shirt is sold at a loss of 20%. What is the ratio of the selling price of the first shirt to the cost price of the second shirt?",
    "options": { "A": "18 : 25", "B": "97 : 100", "C": "24 : 25", "D": "27 : 50" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 38,
    text: "Kapil bought 100 frocks at the rate of ₹320 per frock. Transport expenditure was ₹1000. He paid a tax of ₹1.50 per frock and the labor fee was ₹500. What should be the selling price per frock if she wants to make a profit of 10%?",
    "options": { "A": "₹385.45", "B": "₹370.15", "C": "₹390.80", "D": "₹336.50" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 39,
    text: "Akshay has 30 articles, each having the same cost price. He marked the price of each article at 30% above its cost price. He sold 15 of the articles at a discount of 20% each and the remaining 15 articles at a discount of 10% each, thereby gaining a total profit of ₹630. What was the cost price of each article?",
    "options": { "A": "₹ 240", "B": "₹ 180", "C": "₹ 280", "D": "₹ 200" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 40,
    text: "A dishonest dealer is selling sugar at Rs. 40 per kg and pretending that he is selling it at a loss of Rs. 5 per kg but he actually gives 800g instead of 1 kg, using a faulty weight. What is his actual profit or loss percent?",
    "options": { "A": "Gain, 11%", "B": "Gain, 11 1/9%", "C": "Loss. 10 1/9%", "D": "Loss, 9 1/9%" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 41,
    text: "A woman sold her earphone for Rs. 2,000 and got a percentage profit equal to the numerical value of cost price. The cost price of the earphone is:",
    "options": { "A": "Rs. 500", "B": "Rs. 200", "C": "Rs. 600", "D": "Rs. 400" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 42,
    text: "A manufacturer sells an item to a wholesale dealer at a profit of 11%. The wholesaler sells the same to a retailer at a profit of 15%. The retailer in turn sells it to a customer for ₹17,045, thereby earning a profit of 19%. The cost price of the manufacturer is (consider integral part only) :",
    "options": { "A": "₹13,520", "B": "₹15,020", "C": "₹10,200", "D": "₹11,220" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 43,
    text: "Aditya sells two wrist watches from his personal collection for ₹12,600 each. On the first watch he gains 26% and on the second he loses 10%. Find the overall loss or profit percentage?",
    "options": { "A": "Gain of 16%", "B": "Gain of 5%", "C": "Loss of 5%", "D": "Gain of 12%" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 44,
    text: "Sushant buys goods worth Rs.8000. He gets a discount of 10% on that article. After getting the exemption, he pays tax at the rate of 7.5%. Find the amount he will have to pay for this goods received at his residence, if the shopkeeper charges Rs.200 for home delivery.",
    "options": { "A": "Rs.7940", "B": "Rs.8155", "C": "Rs.9660", "D": "Rs.6851" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 45,
    text: "The difference between the selling prices of some apples, if sold for ₹12 per apple instead of ₹9 per apple, is ₹870. If total cost price of all the apples is ₹2,320, then find the selling price of one apple if the profit earned is 25%",
    "options": { "A": "₹15", "B": "₹10", "C": "₹12", "D": "₹8" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 46,
    text: "Joseph bought two woollen jackets for Rs. 2100 and Rs. 3150 respectively. By selling the first at a gain of k% and the second at a loss of k%, he found the selling price of both is the same. What is the value of k?",
    "options": { "A": "20", "B": "22.64", "C": "15", "D": "25" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 47,
    text: "When an article is sold for Rs.720, there is a profit of x%. When the same article is sold for Rs.750, profit is (x + 5) %. What is the value of x ?",
    "options": { "A": "20", "B": "18", "C": "25", "D": "1" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 48,
    text: "35% of goods were sold at a profit of 65%, while the remaining were sold at x% loss. If the overall loss is 12%, then what is the value of x? (correct to one decimal place)",
    "options": { "A": "51.8", "B": "50.6", "C": "53.5", "D": "52.4" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 49,
    text: "How many kg of salt costing Rs. 28 per kg must be mixed with 6.6 kg of salt costing Rs. 16 per kg, so that selling the mixture at Rs. 29.90, there is a gain of 15%?",
    "options": { "A": "33", "B": "31", "C": "35", "D": "32" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 50,
    text: "By selling two articles for Rs 800, a person gains the cost price of three articles. The profit percent is:",
    "options": { "A": "125", "B": "140", "C": "120", "D": "150" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 51,
    text: "An article is sold at a certain price. If it is sold at 33 1/3 % of this price, there is a loss of 33 1/3 %. What is the percentage profit when it is sold at 60% of the original selling price?",
    "options": { "A": "20", "B": "30", "C": "33 1/3", "D": "17 1/3" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 52,
    text: "Sujata sold 25 articles for Rs. 1250 and she incurred a loss of 10%. How many articles should she sell for Rs. 2600 so that she can get a profit of 17% ?",
    "options": { "A": "26", "B": "40", "C": "25", "D": "42" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 53,
    text: "The sum of cost prices of A and B is Rs. 1200. The sum of the selling prices of A and B is Rs. 1390. If the profit of 10% and 20% is obtained on A and B respectively, then find the ratio between the cost prices of A and B.",
    "options": { "A": "5 : 7", "B": "5 : 9", "C": "7 : 13", "D": "6 : 11" },
    "correct_answer_index": 0,
    year: null
  },
  {
    question_number: 54,
    text: "A shopkeeper earns the same percent of profit as well as loss by selling two similar pieces of furniture for Rs 18000 and Rs 10000, respectively. At what price should he sell it to earn a profit of 50%?",
    "options": { "A": "Rs 21,000", "B": "Rs 20,250", "C": "Rs 21,750", "D": "Rs 19,500" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 55,
    text: "A shopkeeper gains 400% on a transaction. If the cost increases by 100% and there is no change in the selling price, then find the ratio between new profit and selling price.",
    "options": { "A": "1 : 3", "B": "2 : 5", "C": "3 : 5", "D": "1 : 2" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 56,
    text: "Parikh sold his pen at a profit of Rs 11. He calculated the profit percentage on selling price and found it to be 25%. the cost price (in Rs) of the pen is:",
    "options": { "A": "33", "B": "24", "C": "36", "D": "44" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 57,
    text: "If 20% of the goods are sold at 50% profit, 40% of the goods at 20% loss, 20% of the goods at 5% loss and the remaining at no loss or no profit, then the overall profit percentage is:",
    "options": { "A": "5%", "B": "8%", "C": "4%", "D": "1%" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 58,
    text: "Two articles were sold for Rs 2400 each by a shopkeeper. The shopkeeper incurred no profit and no loss on the whole transaction. If one of the two articles sold at a profit of 20%, then what was the loss incurred on the other article?",
    "options": { "A": "600", "B": "400", "C": "380", "D": "240" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 59,
    text: "P sold an article to Q at a profit of 20%. Q sold the same article to R at a loss of 25%. R sold the same article to T at a profit of 50%. If P bought the article at Rs 100, then at what price did T buy that article?",
    "options": { "A": "145", "B": "125", "C": "115", "D": "135" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 60,
    text: "A sold an article on 15% profit for Rs. 1495. He purchased another article whose cost price was equal to that of the first article. He sold this new article at 10% profit. What is the total profit of A ?",
    "options": { "A": "325", "B": "450", "C": "375", "D": "425" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 61,
    text: "The cost prices of article A and article B are Rs. 1200 and Rs. 1600 respectively. The selling price of article A is Rs. 1380 and the total profit after selling both the articles is 25%. What is the profit percentage on the article B ?",
    "options": { "A": "27.5", "B": "32.5", "C": "29.5", "D": "35.5" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 62,
    text: "An article is sold for Rs 6500 so as to earn a profit of 4%. A second article whose cost price is Rs 3750, is sold at a loss of 4%. What is the overall gain or loss percent in the whole transaction?",
    "options": { "A": "Gain 45%", "B": "Loss 1%", "C": "Loss 4%", "D": "Gain 1%" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 63,
    text: "A man bought three articles for Rs 3,000 each. He sold the articles respectively at 10% profit, 5% profit and 15% loss. The total percentage profit/loss he earned is:",
    "options": { "A": "10% loss", "B": "5% loss", "C": "5% profit", "D": "No profit no loss" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 64,
    text: "A person sells an article at a profit of 12%. If he had purchased it for 12% less and sold it for Rs.9 less, he would have gained 27%. What is the original cost price of the article?",
    "options": { "A": "4,250", "B": "4,000", "C": "4,500", "D": "3,750" },
    "correct_answer_index": 3,
    year: null
  },
  {
    "question_number": 65,
    text: "Sushma bought 6 tables and 12 chairs for Rs.12000. She sold the tables at a profit of 15% and the chairs at a loss of 10%. If her total gain was 300, then the total cost of the tables was:",
    "options": { "A": "6000", "B": "5000", "C": "5400", "D": "4800" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 66,
    text: "Abhi bought two articles for Rs.624. He sold one at a loss of 14% and the other at a profit of 14%. If the selling price of both the articles is equal, then the difference between their cost prices (in Rs) is:",
    "options": { "A": "89.64", "B": "87.36", "C": "89.68", "D": "88.84" },
    "correct_answer_index": 1,
    year: null
  },
  {
    "question_number": 67,
    text: "The marked price of an article is Rs. 315. It is sold for Rs. 288. If there is a loss of 4%, then by what percent above the cost is the article marked?",
    "options": { "A": "5%", "B": "8%", "C": "6%", "D": "5 1/2%" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 68,
    text: "A person sold an article at a loss of 15%. Had he sold it for Rs. 30.60 more, he would have gained 9%. To gain 10%, he should have sold it for:",
    "options": { "A": "Rs. 140.25", "B": "Rs. 132", "C": "Rs. 130", "D": "Rs. 128.40" },
    "correct_answer_index": 0,
    year: null
  },
  {
    "question_number": 69,
    text: "A bought 38 kg. Rice at Rs. 54.50/kg, 45 Kg rice at Rs. 62/kg, and 55 kg rice at Rs. 48/kg . He sold the mixture at Rs. 65/kg. His loss or profit percentage is:",
    "options": { "A": "Loss 1.04", "B": "Loss 1.7", "C": "Profit 19.6", "D": "Profit 16.8" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 70,
    text: "Three partners A, B and C share profit and losses in the ratio 3 : 4 : 7 If the profit for the year before charging 30% tax is Rs. 1,10,166 What is B’s share of profit after tax?",
    "options": { "A": "Rs.9442.80", "B": "Rs.31476", "C": "Rs.22033.20", "D": "Rs.24673.10" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 71,
    text: "A cyclist sells 3 cycles at the loss of Rs. 129 per bicycle and 12 cycles on the profit of 516 per cycle. If the total profit on all the bicycles sold is 15%, then what will be the cost per cycle?",
    "options": { "A": "2960", "B": "3870", "C": "2580", "D": "4440" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 72,
    text: "A manufacturer sells the product to a wholesaler at 6% profit, the wholesaler sells the product to a retailer at 8% profit and the retailer sells the product to his customer at 10% profit. The price paid by the customer is Rs 31,482. The cost of the product to the manufacturer is:",
    "options": { "A": "28,306", "B": "26,524", "C": "25,000", "D": "26,980" },
    "correct_answer_index": 2,
    year: null
  },
  {
    "question_number": 73,
    text: "Kusum purchased 22 liters of milk at ₹42 per liter and another 15 liters of milk at ₹50 per liter. She combined both quantities and then sold the entire mixture at ₹48 per liter. What was her total profit or loss ?",
    "options": { "A": "Loss of ₹102", "B": "Profit of ₹102", "C": "Profit of ₹51", "D": "Loss of ₹51" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 74,
    text: "A fruit seller sells apples at a loss of 10 % on the cost price but uses a weight that is 25% less than the actual weight. Find his total profit percentage.",
    "options": { "A": "16.626%", "B": "16.257%", "C": "20%", "D": "18.757%" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 75,
    text: "The profit made on an item sold for ₹2200 is equal to the loss incurred when it is sold for ₹1800. What will be the profit or loss percentage if the item is sold for ₹2150 ?",
    "options": { "A": "Profit of 7.25%", "B": "Loss of 5.5%", "C": "Profit of 7.5%", "D": "Loss of 5.25%" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 76,
    text: "A Shopkeeper sold 15 lunch boxes for ₹3000 and gained a profit of 25%. How many lunch boxes should he sell for ₹2816 to make a profit of 10% ?",
    "options": { "A": "14", "B": "16", "C": "20", "D": "19" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 77,
    text: "A trader sells one brand of coffee at ₹150 per kg, incurring a 25% loss. He also sells another brand of coffee at ₹200 per kg, incurring a 20% loss. If he mixes the two brands in equal proportions and sells the mixture at ₹175 per kg, what is his overall profit or loss percentage ?",
    "options": { "A": "Loss of 22.22%", "B": "Profit of 20.20%", "C": "Loss of 20.20%", "D": "Profit of 22.22%" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 78,
    text: "A tea seller bought 20 kg of Darjeeling tea at ₹310 per kg and 15 kg of Assam tea at ₹220 per kg. He mixed them together. Due to a slight drop in market prices, he had to sell the entire mixture at ₹260 per kg. Calculate his total profit or loss.",
    "options": { "A": "Loss of ₹400", "B": "Profit of ₹400", "C": "Loss of ₹200", "D": "Profit of ₹200" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 79,
    text: "A car dealer sold three cars, A, B, and C, whose selling prices were in the ratio 5 : 4 : 6. He made a profit of 50% on car A, a loss of 10% on car B, and an equal loss (no profit or loss) on car C. What was his approximate profit or loss percentage on the total transaction ?",
    "options": { "A": "loss of 8.88%", "B": "profit of 8.88%", "C": "profit of 10.88%", "D": "loss of 10.88%" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 80,
    text: "Three varieties of lentils, priced at ₹50/kg, ₹40/kg, and a third at an unknown price, are mixed in the ratio 3 : 2 : 5. If the resulting mixture is sold at ₹55/kg, making a profit of 10% on the cost price, what is the price per kg of the third variety of lentils ?",
    "options": { "A": "₹53.50", "B": "₹55.50", "C": "₹54.00", "D": "₹62.50" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 81,
    text: "A vendor mixes two types of rice – one costing ₹110 per kg and the other costing ₹170 per kg, in the ratio 2 : 3. If he sells the mixed variety at ₹142 per kg, find his gain or loss percent.",
    "options": { "A": "2.74% loss", "B": "2.74% gain", "C": "3.25% Loss", "D": "3.25% Gain" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 82,
    text: "A shopkeeper made a loss of ₹135 on an article. If the loss percentage was 10%, what was the cost price of the article (in ₹)?",
    "options": { "A": "₹1347", "B": "₹1345", "C": "₹1350", "D": "₹1400" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 83,
    text: "Two varieties of rice are sold at ₹72 per kg and ₹60 per kg respectively, with profit percentages of 20% and 25%. When they are mixed in the ratio 2 : 1 and sold at ₹70 per kg, calculate the net percentage gain or loss.",
    "options": { "A": "Profit of 50%", "B": "Loss of 25%", "C": "Profit of 25%", "D": "Loss of 50%" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 84,
    text: "A clothing store sold three dresses, D1, D2, and D3, whose selling prices were in the ratio 12 : 6 : 3 . They made a profit of 20% on D1, a loss of 10% on D2, and a profit of 5% on D3. What was their approximate total profit or loss percentage for the entire sale ?",
    "options": { "A": "profit of 7.58%", "B": "loss of 10.78%", "C": "profit of 10.78%", "D": "loss of 7.58%" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 85,
    text: "A shopkeeper mixes 50 kg of sugar costing ₹60 per kg with a certain quantity of sugar costing ₹90 per kg. If he sells the mixture at ₹84 per kg and makes a 20% profit, find the quantity of the second type of sugar that was mixed.",
    "options": { "A": "30 kg", "B": "25 kg", "C": "20 kg", "D": "15 kg" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 86,
    text: "A fruit seller buys three varieties of mangoes. The first variety is bought at 8 for ₹20, the second at 10 for ₹24, and the third at 4 for ₹10. He mixes them in the ratio 2 : 3 : 1 respectively. If he sells all the mangoes at 6 for ₹14, what is his approximate gain or loss percentage ?",
    "options": { "A": "Profit of 4.76%", "B": "Loss of 4.76%", "C": "Loss of 6%", "D": "Profit of 6%" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 87,
    text: "A flower vendor bought 300 flowers for ₹900. 90 flowers withered and became unsellable. At what price per flower should he sell the remaining flowers to earn a profit of 40% on his total cost ?",
    "options": { "A": "₹7", "B": "₹6", "C": "₹5", "D": "₹3" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 88,
    text: "The ratio of the profit to the cost price of a product is 3 : 8. What is the ratio of its selling price to its profit ?",
    "options": { "A": "7 : 2", "B": "11 : 10", "C": "5 : 15", "D": "11 : 3" },
    "correct_answer_index": 3,
    year: "2025"
  },
  {
    "question_number": 89,
    text: "A shop sells a shirt for ₹ P , incurring a loss of 10%. They mark it up to ₹1.8P and then provide a 20% discount. What is the percentage profit or loss ?",
    "options": { "A": "24.6% Profit", "B": "28.6% Loss", "C": "29.6% Profit", "D": "34.6% Loss" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 90,
    text: "A shopkeeper mixes two types of pulses costing ₹80/kg and ₹100/kg. He sells the mixture at ₹112.5/kg, earning a 25% profit. In what ratio did he mix the two types of pulses ?",
    "options": { "A": "1 : 3", "B": "1 : 1", "C": "3 : 2", "D": "4 : 1" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 91,
    text: "A stationery shop owner buys three types of pencils. The first type costs him 10 pencils for ₹20, the second 3 pencils for ₹9, and the third 9 pencils for ₹45. He mixes them in the ratio 3 : 4 : 3. If he sells all the pencils at 4 for ₹21, what is his approximate gain or loss percentage ?",
    "options": { "A": "Loss of 59.09%", "B": "Profit of 59.09%", "C": "Profit of 60%", "D": "Loss of 60%" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 92,
    text: "A shopkeeper mixes two qualities of Rice. The first quality costs ₹150 per kg and is mixed with the second quality in the ratio 4 : 5. If the mixture is sold at ₹130 per kg (at no profit, no loss), what is the cost per kg of the second quality of Rice ?",
    "options": { "A": "₹100", "B": "₹110", "C": "₹114", "D": "₹120" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 93,
    text: "A grocer purchased 40 kg of rice at ₹40 per kg and 30 kg of another variety of rice at ₹55 per kg. He mixed the two varieties and sold the entire mixture at ₹48 per kg. Find his total profit or loss in this transaction.",
    "options": { "A": "Loss of ₹110", "B": "Loss of ₹240", "C": "Profit of ₹110", "D": "Loss of ₹290" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 94,
    text: "A Smart watch retailer sells a Smart watch for ₹P and earns a profit of 20%. For a special festive offer, he marks the same Smart watch at ₹1.5P . At the offer, he provides a discount of 10%. What will be the percentage profit that he will make during the festive offer?",
    "options": { "A": "36%", "B": "46%", "C": "62%", "D": "60%" },
    "correct_answer_index": 2,
    year: "2025"
  },
  {
    "question_number": 95,
    text: "If the ratio between the loss and cost price of an article is 1 : 5, then the ratio between its selling price and cost price is_______.",
    "options": { "A": "9 : 10", "B": "4 : 5", "C": "2 : 5", "D": "7 : 10" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 96,
    text: "A shopkeeper mixes two varieties of pulses - one costing ₹50 per kg and the other costing ₹90 per kg, in the ratio 3 : 1. If he sells the mixed variety at ₹96 per kg, find his gain or loss percent.",
    "options": { "A": "60% Gain", "B": "40% Gain", "C": "45% Loss", "D": "60% Loss" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 97,
    text: "A fruit vendor sells 20 kg of oranges for ₹900, thereby gaining the cost price of 5 kg of oranges. What is his profit percentage ?",
    "options": { "A": "28.65%", "B": "25%", "C": "26%", "D": "31.56%" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 98,
    text: "The cost price of an article is ₹200. A shopkeeper sells it at a discount of 20% on the marked price. If the marked price is ₹400, what is the shopkeeper's profit or loss percentage ?",
    "options": { "A": "60% Profit", "B": "60% Loss", "C": "30% Profit", "D": "30% Loss" },
    "correct_answer_index": 0,
    year: "2025"
  },
  {
    "question_number": 99,
    text: "A grocer mixes two varieties of rice one costing ₹40 per kg and the other costing ₹50 per kg, in the ratio 3 : 5. If he sells the mixed variety at ₹55.50 per kg, find his gain or loss percent.",
    "options": { "A": "20% Loss", "B": "20% Gain", "C": "18% Gain", "D": "18% Loss" },
    "correct_answer_index": 1,
    year: "2025"
  },
  {
    "question_number": 100,
    text: "A can contains 30 litres of oil at Rs. 40/litre. Another can contains 70 litres of oil at Rs. 50/litre. They are mixed, and 25 litres are sold at Rs. 60/litre. How much profit or loss does the seller make on this sale ?",
    "options": { "A": "Rs. 600 profit", "B": "Rs. 325 loss", "C": "Rs. 280 loss", "D": "Rs. 325 profit" },
    "correct_answer_index": 3,
    year: "2025"
  },
  {
    question_number: 101,
    text: "A businessman invests Rs. 40,000 in buying a bike and spends Rs. 8,000 on transportation and Rs. 7,000 on storage. If he sells the bike for Rs. 60,000, what is the profit or loss percentage ?",
    options: { A: "9.09 % Profit", B: "8.42% loss", C: "8.26% loss", D: "5.26% Profit" },
    correct_answer_index: 0,
    year: "2025"
  },
  {
    question_number: 102,
    text: "A person invested in two items - one gave a 8% profit and the other a 6% loss. If the total investment was Rs. 6,000 and the net result was a Rs. 200 profit, what was the investment in the profit-making item?",
    options: { A: "Rs. 4,000", B: "Rs. 3,500", C: "Rs. 4,500", D: "Rs. 3,000" },
    correct_answer_index: 0,
    year: "2025"
  },
  {
    question_number: 103,
    text: "A seller mixes two varieties of rice costing Rs. 80/kg and Rs. 120/kg in a certain ratio and sells the mixture at Rs. 125/kg, gaining 25%. What is the ratio in which the two types are mixed ?",
    options: { A: "1 : 1", B: "2 : 3", C: "3 : 2", D: "4 : 1" },
    correct_answer_index: 0,
    year: "2025"
  },
  {
    question_number: 104,
    text: "Amit buys a set of 3 identical watches at a total cost of Rs. 3,500. He sells them at Rs. 1,600, Rs. 1,700, and Rs. 1,500, respectively. What is the overall profit or loss ?",
    options: { A: "Rs. 1100 loss", B: "Rs. 1300 profit", C: "Rs. 1600 profit", D: "Rs. 1600 loss" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 105,
    text: "A seller offers a combo deal: \"Buy 4 shirts for the price of 3\". If each shirt costs him Rs. 1500, what is the effective loss percentage ?",
    options: { A: "10%", B: "20%", C: "15%", D: "25%" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 106,
    text: "A combo offer says, \"Buy 3 shirts at Rs. 800 each, get a fourth shirt free.\" What is the effective price per shirt ?",
    options: { A: "Rs. 200", B: "Rs. 600", C: "Rs. 1100", D: "Rs. 400" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 107,
    text: "A shopkeeper bought 200 toys at Rs 50 each. He sold 80% of the toys at 10% profit and the rest at 10% loss. What is the overall profit or loss percentage ?",
    options: { A: "8% profit", B: "6% profit", C: "5% loss", D: "6% loss" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 108,
    text: "A shopkeeper sells two shirts at Rs. 600 each. On one, he gains 20%, and on the other, he loses 20%. What is his net gain or loss ?",
    options: { A: "Rs. 50 loss", B: "Rs. 75 gain", C: "Rs. 40 gain", D: "Rs. 80 loss" },
    correct_answer_index: 0,
    year: "2025"
  },
  {
    question_number: 109,
    text: "If the selling price of an article is 85% of its marked price and the cost price is 75% of the marked price, what is the profit percentage?",
    options: { A: "14 2/7 %", B: "13 1/3 %", C: "16 2/3 %", D: "13 1/3 %" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 110,
    text: "A man buys 10 shirts for Rs. 5,000 and sells 8 of them for Rs. 4,900. If he discards the remaining 2 shirts, what is his overall gain or loss ?",
    options: { A: "Rs. 100 loss", B: "Rs. 50 loss", C: "Rs. 100 profit", D: "Rs. 50 profit" },
    correct_answer_index: 0,
    year: "2025"
  },
  {
    question_number: 111,
    text: "What is the selling price if the cost price is ₹600 and the profit is 20% ?",
    options: { A: "₹620", B: "₹700", C: "₹650", D: "₹720" },
    correct_answer_index: 3,
    year: "2025"
  },
  {
    question_number: 112,
    text: "A shopkeeper buys 50 toys for ₹2,000. He sells 40 of them at ₹50 each and the remaining at ₹30 each. What is his profit or loss percentage ?",
    options: { A: "10%", B: "12%", C: "15%", D: "13%" },
    correct_answer_index: 2,
    year: "2025"
  },
  {
    question_number: 113,
    text: "A wrist watch worth ₹2,000 is sold at a profit of 10%. What is the selling price?",
    options: { A: "₹2,100", B: "₹2,200", C: "₹2,300", D: "₹2,400" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 114,
    text: "A fruit seller sells 3(1/2) kg of mangoes at ₹40/kg and 2.25 kg of apples at ₹60/kg. What is the total cost of the fruits?",
    options: { A: "₹265", B: "₹270.50", C: "₹275", D: "₹280" },
    correct_answer_index: 2,
    year: "2025"
  },
  {
    question_number: 115,
    text: "The cost price of an item is ₹400, and it is sold for ₹320. What is the percentage loss?",
    options: { A: "15%", B: "18%", C: "20%", D: "25%" },
    correct_answer_index: 2,
    year: "2025"
  },
  {
    question_number: 116,
    text: "A product costs ₹800 and is sold for ₹640. What is the loss percentage?",
    options: { A: "10%", B: "15%", C: "20%", D: "25%" },
    correct_answer_index: 2,
    year: "2025"
  },
  {
    question_number: 117,
    text: "A shopkeeper buys a Fan for ₹900 and sells it at a profit of 33 1/3 %. What is the selling price?",
    options: { A: "₹1,100", B: "₹1,200", C: "₹1,250", D: "₹1,300" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 118,
    text: "If the profit on an item is 20% and the cost price is ₹750, find the selling price.",
    options: { A: "₹880", B: "₹900", C: "₹860", D: "₹960" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 119,
    text: "The cost of a flower vase is ₹180. If the shopkeeper sells it at a loss of 25%, at what price is it sold?",
    options: { A: "₹140", B: "₹132", C: "₹135", D: "₹130" },
    correct_answer_index: 2,
    year: "2025"
  },
  {
    question_number: 120,
    text: "The cost price of an article is 50% of its selling price. What is the profit or the loss as percent?",
    options: { A: "100%", B: "120%", C: "50%", D: "25%" },
    correct_answer_index: 0,
    year: "2025"
  },
  {
    question_number: 121,
    text: "A vendor bought 100 mangoes at ₹10 each. He sold 60 of them at ₹12 each and the remaining 40 mangoes at ₹11 each. What is his overall profit or loss percentage?",
    options: { A: "12% profit", B: "14% profit", C: "16% profit", D: "18% profit" },
    correct_answer_index: 2,
    year: "2025"
  },
  {
    question_number: 122,
    text: "A man bought an old TV for ₹20,000. He spent ₹4,000 on its repairs and then sold it for ₹27,000. What is his percentage profit?",
    options: { A: "25%", B: "12.5%", C: "22%", D: "30%" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 123,
    text: "A shopkeeper sells his goods at 80% of their cost price. Find the percent gain or losses.",
    options: { A: "20%", B: "25%", C: "30%", D: "33 1/3 %" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 124,
    text: "A seller buys 300 car. He sells some of them at a gain of 25% and the remaining at a gain of 35%. If he gains 30% on the whole, then how many did he sell at a gain of 25%?",
    options: { A: "100", B: "120", C: "150", D: "180" },
    correct_answer_index: 2,
    year: "2025"
  },
  {
    question_number: 125,
    text: "An article is sold at a 15% loss. If the selling price was ₹300 more, there would have been a 10% gain. What is the cost price of the article?",
    options: { A: "₹1500", B: "₹1800", C: "₹2000", D: "₹1200" },
    correct_answer_index: 3,
    year: "2025"
  },
  {
    question_number: 126,
    text: "An article was sold at a loss of 20%. If it was sold for ₹600 more, then there would have been a gain of 10%. Find the cost price of the article.",
    options: { A: "2000", B: "2400", C: "3000", D: "2500" },
    correct_answer_index: 0,
    year: "2025"
  },
  {
    question_number: 127,
    text: "The cost price of 15 articles is the same as the selling price of 10 articles. What is the profit percent?",
    options: { A: "40%", B: "50%", C: "45%", D: "35%" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 128,
    text: "Some articles were bought at the rate of Rs 6 per 15 articles, and sold at the rate of Rs 5 per 18 articles. Profit percent is:",
    options: { A: "36", B: "40", C: "44", D: "48" },
    correct_answer_index: 2,
    year: "2025"
  },
  {
    question_number: 129,
    text: "A man sells two articles for ₹5000 each. On one, he gains 20%, and on the other, he loses 20%. What is his net gain or loss percentage in the entire transaction?",
    options: { A: "4% gain", B: "4% loss", C: "No gain, no loss", D: "5% loss" },
    correct_answer_index: 1,
    year: "2025"
  },
  {
    question_number: 130,
    text: "A bookstore buys 5000 books for ₹100 each. They offer a \"Buy 3, Get 2 Free\" scheme but sell at the marked price of ₹250 per book. What is their effective profit percentage per book sold (after adjusting for the free books)?",
    options: { A: "50%", B: "10%", C: "25%", D: "Neither profit nor loss" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 131,
    text: "A merchant gains 50% after allowing a discount of 25% on the marked price. Find his profit percentage if no discount were allowed.",
    options: { A: "100%", B: "50%", C: "66.66%", D: "25%" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 132,
    text: "What percentage profit is made when the selling price of 25 books covers the cost price of 75 books?",
    options: { A: "100%", B: "150%", C: "200%", D: "225%" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 133,
    text: "A dealer allows a discount of 20% on marked price but still gains 10%. If the cost price is Rs. 6400, what is the marked price?",
    options: { A: "Rs. 8,800", B: "Rs. 9,400", C: "Rs. 8,000", D: "Rs. 10,000" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 134,
    text: "An online seller purchases a Macbook at ₹80,000. He lists it at a 20% markup. Due to a Diwali festive sale, he gives a flat 5% discount on the listed price and offers free shipping costing him ₹1000. What is the net profit or loss percentage?",
    options: { A: "15%", B: "13%", C: "31%", D: "10%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 135,
    text: "A trader sells two items. On the first item, he makes a profit of 20%, and on the second item, he incurs a loss of 5%. If the selling price of both items is the same (₹10500 each), what is his overall profit or loss percentage on the entire transaction ?",
    options: { A: "6.25% profit", B: "6.05% profit", C: "6.05% loss", D: "No overall profit or loss" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 136,
    text: "The marked price of an article is ₹840. A shopkeeper allows a discount of 20% and still gains 12%. If no discount were allowed, what would have been his gain percentage ?",
    options: { A: "40%", B: "35%", C: "28%", D: "50%" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 137,
    text: "Calculate the profit percentage when the profit is 17% of the cost.",
    options: { A: "17%", B: "21%", C: "19%", D: "11%" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 138,
    text: "A shopkeeper earns 65% profit on selling an article. If he increases the selling price by Rs. 442, the profit becomes 82%. Find the cost price.",
    options: { A: "Rs. 3000", B: "Rs. 2800", C: "Rs. 2600", D: "Rs. 2500" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 139,
    text: "A man sells an article for Rs. 630 and gains 5 %. What is the cost price",
    options: { A: "Rs. 500", B: "Rs. 600", C: "Rs. 550", D: "Rs. 450" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 140,
    text: "A shopkeeper sells mangoes at a loss of 20%. If he had sold them for Rs. 4.5 more per kg, he would have gained 25%. Find the cost price per kg.",
    options: { A: "Rs.10", B: "Rs.11", C: "Rs.9", D: "Rs.8" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 141,
    text: "By selling 15 articles for ₹3,000, a shopkeeper gains the cost price of 3 articles. The profit percent is:",
    options: { A: "15%", B: "20%", C: "25%", D: "33.33%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 142,
    text: "A milkman bought 60 liters of milk for ₹4000. 15 liters of milk spoiled. At what rate per liter should he sell the remaining milk to make a profit of 14% on his total outlay?",
    options: { A: "₹93.33 per liter", B: "₹106.24 per liter", C: "₹101.33 per liter", D: "₹102.82 per liter" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 143,
    text: "A man buys 20 shirts for Rs.10,000 and sells 16 of them for Rs.9,800. If he discards the remaining 4 shirts, what is his overall gain or loss ?",
    options: { A: "Rs. 200 loss", B: "Rs.100 loss", C: "Rs.200 profit", D: "Rs.100 profit" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 144,
    text: "A shopkeeper claims to sell goods at a profit of 20% on the cost price but uses a false weight of 950 g for every 1 kg. What is his approximate actual profit percentage?",
    options: { A: "28.2%", B: "26.3%", C: "12.1%.", D: "10.2%." },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 145,
    text: "A baker made 200 cakes for ₹4000. Due to an accident, 20 cakes were damaged. At what price per cake should he sell the remaining cakes to make an overall profit of 25%?",
    options: { A: "₹43.62", B: "₹27.78", C: "₹29.62", D: "₹38.33" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 146,
    text: "A shopkeeper finds that the profit from selling a watch for ₹1300 is equal to the loss incurred when selling it for ₹700. What will be the percentage loss if the watch is sold for ₹900?",
    options: { A: "10%", B: "12%", C: "15%", D: "16%" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 147,
    text: "The profit obtained by selling a bicycle for ₹940 is the same as the loss incurred if it is sold for ₹860. What will be the percentage profit if the bicycle is sold for ₹1000?",
    options: { A: "16.82%", B: "11.11%", C: "20.26%", D: "19.45%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 148,
    text: "A person sells 40 chairs for ₹8,000, suffering a loss of 20%. How many chairs should he sell for ₹9,000 to make a profit of 20%?",
    options: { A: "25", B: "30", C: "26", D: "27" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 149,
    text: "Sandeep made a profit of 22% when he sold an overcoat for 8,540. Find the cost price of the overcoat.",
    options: { A: "₹ 7,500", B: "₹ 7,000", C: "₹ 6,000", D: "₹ 6,500" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 150,
    text: "Atul sold two sacks of rice for ₹19,200 each. On one, he gained 20% and on the other, he lost 20%. Find his gain or loss percentage in the whole transaction.",
    options: { A: "8% profit", B: "7% profit", C: "4% loss", D: "5% loss" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 151,
    text: "Two mixers and one TV cost ₹7,000, while two TVs and one mixer cost ₹9,800. The value of one TV is:",
    options: { A: "₹3,600", B: "₹4,600", C: "₹3,200", D: "₹4,200" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 152,
    text: "A shopkeeper makes a 15% profit on a sale. He would have made 18%, if he had sold it for Rs.18 more. The cost price of the article is:",
    options: { A: "Rs.650", B: "Rs.550", C: "Rs.600", D: "Rs.500" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 153,
    text: "By selling an article for ₹19, a dealer makes a profit of 20%. By how much should he increase his selling price (in ₹, rounded off to two decimal place) so as to make a profit of 40% ?",
    options: { A: "6.17", B: "3.17", C: "4.17", D: "5.17" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 154,
    text: "A vendor wants to gain 25% by adding water to milk and selling the mixture at the cost price. Find the ratio of water and milk in the mixture.",
    options: { A: "2 : 5", B: "1 : 4", C: "2 : 7", D: "1 : 5" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 155,
    text: "A flat worth ₹9,50,000 is sold by Lakshman to Bharath at 8% profit. If Bharath sells it back to Lakshman at 3% loss, then find the gain/loss (in ₹) of Lakshman in the entire transaction ?",
    options: { A: "Lakshman gains ₹30,780", B: "Lakshman gains ₹50,200", C: "Lakshman gains ₹45,220", D: "Lakshman loses ₹45,220" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 156,
    text: "Two vendors calculate their profit percentage on the cost price and selling price, respectively. What will be the difference between the profits (in ₹) if both the vendors declare a profit of 28% on the goods sold for ₹3,200 ?",
    options: { A: "196", B: "700", C: "548", D: "896" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 157,
    text: "Each of the two merchants sell an article for ₹1,000. If Merchant A computes his profit on the cost price, while Merchant B computes his profit on the selling price, then they both end up making profits of 25%. By how much is the profit made by Merchant B more than that of Merchant A ?",
    options: { A: "₹45", B: "₹40", C: "₹35", D: "₹50" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 158,
    text: "A trader sells his goods at 25% profit. Had he bought it at 10% more and sold it for ₹75 more, he would have earned a profit of 25%. The cost price of the goods is:",
    options: { A: "₹ 400", B: "₹ 1000", C: "₹ 600", D: "₹ 800" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 159,
    text: "The cost price of some table lamps is ₹25,000. The shopkeeper will get ₹15,000 more If he sells these table lamps for ₹1,200 per lamp instead of ₹900 per lamp. Find the selling price of 23 table lamps if he earned 21% profit.",
    options: { A: "₹14,917", B: "₹13,915", C: "₹12,919", D: "₹12,585" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 160,
    text: "A vendor bought a certain number of bananas at 6 for ₹5 and sold them at 4 for ₹3. Find his loss percentage.",
    options: { A: "12%", B: "10%", C: "8%", D: "15%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 161,
    text: "Pankaj bought a watch at a price range from₹1,500 to₹3,000 which are sold at prices ranging from₹2,500 to₹3,500. If Pankaj sells such 10 watches, then the greatest possible profit (in ₹) he made with the transaction is:",
    options: { A: "19,000", B: "23,854", C: "21,765", D: "20,000" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 162,
    text: "Vasudha claimed to sell her items at 18% above the cost of production, but used a weight that had 1 kg written on it, though it actually weighed y grams. If the actual profit percentage earned by Vasudha was 33 1/3 %, what is the value of y ?",
    options: { A: "885", B: "890", C: "895", D: "880" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 163,
    text: "A shopkeeper sells one-fourth of his items at a loss of 12%, one-third of the remaining items at a profit of 44%, and the rest at a loss of 7%. What is his overall profit/loss percentage ?",
    options: { A: "2% loss", B: "4.5% gain", C: "4.5% loss", D: "2% gain" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 164,
    text: "Find the gain percentage, given that Komal sold her scooter for 1980 ₹ gaining 1/5 th of the selling price.",
    options: { A: "20%", B: "45%", C: "40%", D: "25%" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 165,
    text: "The amount of profit and loss will be the same if an article is sold at ₹19,125 and ₹14,625. Find the percentage of profit if an article is sold at ₹19,125.",
    options: { A: "12 1/4 %", B: "13 1/3 %", C: "12 3/4 %", D: "11 1/4 %" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 166,
    text: "Which of the following equations is correct ?",
    options: { A: "Gain % = CP / (gain × 100)", B: "SP = (100 - gain%) × CP / 100", C: "SP = (100 - loss%) × CP / 100", D: "Loss = SP - CP" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 167,
    text: "A grocer professes to sell rice at the cost price, but uses a fake weight of 870 g for 1 kg. Find his profit percentage (correct to two decimal places).",
    options: { A: "15.11%", B: "14.94%", C: "18.21%", D: "11.11%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 168,
    text: "Madhav purchased an item for ₹42,000 and sold it at a loss of 20%. With that amount, he purchased another item and sold it at a gain of 30%. What is the overall gain (in ₹)?",
    options: { A: "6720", B: "4200", C: "1680", D: "2520" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 169,
    text: "The marked price of an article is 26% more than its cost price. If a discount of 32% is given, what will be the loss percentage?",
    options: { A: "18.64%", B: "15.25%", C: "12.26%", D: "14.32%" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 170,
    text: "A dishonest shopkeeper claims to sell salt at a rate of ₹25/kg. The cost price of the salt is ₹25/kg. Not satisfied with this, he tries to make profit by removing 200 gm from each kg. What is the shopkeeper’s gain percentage?",
    options: { A: "15%", B: "25%", C: "30%", D: "20%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 171,
    text: "A merchant has 1000 kg of sugar, part of which he sells at a 10% profit and the rest at a 40% profit. He gains 20% on the whole. The quantity sold at 40% profit is:",
    options: { A: "543 1/3 kg", B: "383 1/3 kg", C: "333 1/3 kg", D: "443 1/3 kg" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 172,
    text: "Ravi's salary was increased by 50%. After some time, his new salary was also increased by 50%. Find his gain percentage of salary.",
    options: { A: "125%", B: "100%", C: "200%", D: "150%" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 173,
    text: "A dishonest merchant sells his grocery using weights that are 12% less than the true weights and makes a profit of 10%. Find his total gain percentage.",
    options: { A: "10%", B: "20%", C: "15%", D: "25%" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 174,
    text: "S borrowed some amount from R and promised to pay him 8% interest. Then S invested the borrowed amount in a scheme, upon which he earned a profit of 5% after paying R, the principal amount with interest. How much percentage R would have gained, if he would have invested in the scheme directly?",
    options: { A: "13.4%", B: "13%", C: "14.4%", D: "14%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 175,
    text: "The cost price of a bat is 75% of the marked price. Calculate the gain percentage after allowing a discount of 15%.",
    options: { A: "25.6%", B: "13.33%", C: "18.16%", D: "21.33%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 176,
    text: "Find the gain percentage, given that Siddhi sold her scooter for ₹ 24318 gaining 1/6 th of the selling price.",
    options: { A: "20%", B: "35%", C: "25%", D: "5%" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 177,
    text: "The profit gained on selling a certain product is 320% of the cost. If the cost increases by 10% but the selling price remains constant, then what percentage of the selling price is the profit (correct to one decimal place)?",
    options: { A: "70.2%", B: "73.8%", C: "75.7%", D: "63.8%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 178,
    text: "An article is sold at a profit of 250%. What is the ratio of its cost price to selling price?",
    options: { A: "2 : 5", B: "5 : 2", C: "2 : 7", D: "7 : 2" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 179,
    text: "Ramesh sells rice at ₹36 per kg, which he purchased for ₹30 per kg. Moreover, he gives only 800 g of rice instead of 1 kg while selling. Find the actual profit percentage of Ramesh.",
    options: { A: "46%", B: "50%", C: "48%", D: "52%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 180,
    text: "A shopkeeper marked the price 20% more than its cost price. If he allows a discount of 30%, then find his loss percent.",
    options: { A: "20%", B: "16%", C: "25%", D: "15%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 181,
    text: "In a bank, 6% interest is given on the deposited amount. The bank then invests the money in the stock market and is able to earn ₹30,000 for every ₹3,00,000. How much money is the bank earning finally if the total amount deposited in the bank is ₹60,00,000?",
    options: { A: "₹3,00,000", B: "₹6,40,000", C: "₹2,40,000", D: "₹3,60,000" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 182,
    text: "Ajay spends 66 2/3 % of his income on different household items. If his income increases by 25% and expenditure increase by 20%, then the effect on his savings will be:",
    options: { A: "28%", B: "61%", C: "49%", D: "35%" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 183,
    text: "A shopkeeper sold 5/8 of his articles at a gain of 20% and the remaining at the cost price. What is his gain percentage in the whole transaction?",
    options: { A: "16 1/2 %", B: "14 1/2 %", C: "13 1/2 %", D: "12 1/2 %" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 184,
    text: "From the given data, find the ratio of the cost prices of a shirt and a trouser. (Shirt Selling Price ₹1,200 Profit 20%, Trouser Selling Price ₹660 Profit 10%)",
    options: { A: "2 : 1", B: "1 : 3", C: "3 : 4", D: "5 : 3" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 185,
    text: "A shopkeeper sells rice at the rate of ₹44 per kg whose cost price is ₹40 per kg. Not satisfied with this, he tries to increase his profit by removing 200 grams of rice from each packet. What is the shopkeeper’s overall gain percentage?",
    options: { A: "35%", B: "37.5%", C: "37%", D: "35.5%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 186,
    text: "The marked price of 55 items was equal to the cost price of 99 items. The selling price of 56 items was equal to the marked price of 35 items. Calculate the profit or loss percentage from the sale of each item.",
    options: { A: "15% profit", B: "12.25% profit", C: "12.5% profit", D: "12.5% loss" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 187,
    text: "A customer pays ₹975 in instalments. The payment is done each month ₹5 less than the previous month. If the first instalment is ₹100, how much time will be taken to pay the entire amount?",
    options: { A: "14 months", B: "15 months", C: "27 months", D: "26 months" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 188,
    text: "Samreen sells a keyboard for ₹1,260 at a profit of 25%, and another keyboard for ₹1,440 at a loss of 10%. What is her total gain or loss percentage?",
    options: { A: "3 11/86 % Loss", B: "3 163/86 % Gain", C: "3 27/86 %Loss", D: "3 11/163 % Gain" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 189,
    text: "A person purchased a table and a sofa for ₹28,000. He sold the sofa at a profit of 10% and the table at a profit 15.25%. If his total profit was 13%, then the difference between the cost price of the sofa and the table (in ₹) is:",
    options: { A: "1500", B: "4000", C: "5000", D: "2500" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 190,
    text: "If the market price of a bag is 25% above the cost price, and a discount of 18% is declared on it, then find the gain percentage.",
    options: { A: "1.5%", B: "2.0%", C: "3.0%", D: "2.5%" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 191,
    text: "Rohini buys a Bluetooth headphone set for ₹1,700 from a wholesale shop and marks it at ₹2,000. Later on, she allows a discount of 40% on its sale. What is her loss or gain percentage (correct up to two decimal places)?",
    options: { A: "25.19% loss", B: "29.41% gain", C: "29.41% loss", D: "25.19% gain" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 192,
    text: "Ramesh purchased 130 books at the rate of ₹200 each and sold half of them at the rate of ₹300 each, one-fifth of them at the rate of ₹350 each and the rest at the cost price. Find his profit percentage.",
    options: { A: "35%", B: "40%", C: "38%", D: "44%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 193,
    text: "A man loses 28% by selling an article for ₹144. If he sells it for ₹288, what will be his gain/loss percentage?",
    options: { A: "Gain, 41%", B: "Loss, 43%", C: "Gain, 44%", D: "Loss, 46%" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 194,
    text: "An article passing through two hands is sold at a total profit of 40% of the original cost price. If the first dealer makes a profit of 30%, then the profit percentage made by the second dealer is:",
    options: { A: "8 6/13 %", B: "6 9/13 %", C: "7 1/13 %", D: "7 9/13 %" },
    correct_answer_index: 3,
    year: null
  },
  {
    question_number: 195,
    text: "An article costs ₹1,000 for a salesman. He fixes its marked price as ₹1,500. He sells it to a customer at a discount of 20%, He gives a further discount of 10% for each cash payment. Find the percentage of loss or gain that the salesman makes on sale.",
    options: { A: "gain 8%", B: "gain 10%", C: "loss 8%", D: "loss 10%" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 196,
    text: "A shopkeeper marks up the price of the oil by 40% and uses a faulty machine which measures 15% less. If the shopkeeper gives a discount of 32%, the profit/loss percentage is:",
    options: { A: "12% Profit", B: "25% Profit", C: "15% Loss", D: "18% Loss" },
    correct_answer_index: 0,
    year: null
  },
  {
    question_number: 197,
    text: "Ravi sells his goods at a 25% loss on cost price but uses 45% less weight. What is his percentage profit or loss?",
    options: { A: "Loss, 47 9/11 %", B: "Loss, 36 4/11 %", C: "Profit, 36 4/11 %", D: "Profit, 47 9/11 %" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 198,
    text: "A shopkeeper gives a 10% discount and still earns 10% profit. The marked price of the item is how many times (correct to 2 decimal places) the cost price?",
    options: { A: "1.28", B: "1.20", C: "1.22", D: "1.24" },
    correct_answer_index: 2,
    year: null
  },
  {
    question_number: 199,
    text: "If the selling price of 100 pens is equal to the cost price of 140 pens, find the profit percentage.",
    options: { A: "30%", B: "40%", C: "45%", D: "36%" },
    correct_answer_index: 1,
    year: null
  },
  {
    question_number: 200,
    text: "A merchant sold two refrigerators for ₹10,000 each. On one refrigerator, he incurred a 20% loss, and on the other, he gained 20%. What was his profit/loss percentage on the whole transaction?",
    options: { A: "Profit of 2%", B: "Loss of 2%", C: "Loss of 4%", D: "Profit of 4%" },
    correct_answer_index: 2,
    year: null
  }
  ],
});