window.BASE_CHAPTERS = window.BASE_CHAPTERS || [];
window.BASE_CHAPTERS.push({
  id: "RatioProportion",
  title: "Ratio and Proportion",
  desc: "SSC CGL PYQs focused on Ratio and Proportion.",
  questions: [
  {
    question_number: 1,
    text: "A bag contains ₹5, ₹2, and ₹1 coins in the ratio 2 : 3 : 5. If the total amount of money in the bag is ₹252, find the number of coins of each kind.",
    options: { A: "16 coins of ₹5, 24 coins of ₹2, and 40 coins of ₹1", B: "20 coins of ₹5, 30 coins of ₹2, and 50 coins of ₹1", C: "24 coins of ₹5, 36 coins of ₹2, and 60 coins of ₹1", D: "18 coins of ₹5, 27 coins of ₹2, and 45 coins of ₹1" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 2,
    text: "If 9A = 10B and 12B =13C, find the ratio A : C",
    options: { A: "15 : 16", B: "39 : 40", C: "27 : 28", D: "65 : 54" },
    correct_answer_index: 3,
    year: "2025",
  },
  {
    question_number: 3,
    text: "The savings of two persons are in the ratio 8 : 7 . If the first person increases his savings by 20% and the second person increases his savings by 15% , find the new ratio of their savings.",
    options: { A: "32 : 28", B: "46 : 40.25", C: "9.6 : 8.05", D: "184 : 161" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 4,
    text: "A scholarship amount of ₹1500 is to be distributed between A and B in the ratio 7:5. An amount of ₹250 is deducted for administrative charges; the remaining amount is increased by 20% as a bonus before the final distribution. How much amount will student A receive?",
    options: { A: "₹875", B: "₹900", C: "₹833.33", D: "₹800" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 5,
    text: "In a zoo, there are horse and pigeons. If heads are counted, there are 200 heads and if legs are counted there are 580 legs. How many pigeons are there?",
    options: { A: "90", B: "110", C: "100", D: "120" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 6,
    text: "A recipe needs 4 cups of sugar to make 16 cookies. How many cups of sugar are needed to make 24 cookies in the same proportions?",
    options: { A: "5 cups", B: "8 cups", C: "6 cups", D: "7 cups" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 7,
    text: "The number of marbles in three bags is in the ratio of 2 : 3 : 4. If 12 marbles are added to each bag, then the ratio changed to 8 : 11 : 14. The total number of marbles in the beginning was:",
    options: { A: "216", B: "162", C: "200", D: "126" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 8,
    text: "A function of two variable varies directly with x and inversely with y. Determine function when x = 5 and y = 3. Given that, for x = 0 and y = 1, f = 15 and for x = 1 and y = 15, f = 2.",
    options: { A: "10", B: "2", C: "5", D: "15" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 9,
    text: "A payment of ₹120 is made with ₹10, ₹5 and ₹2 coins. A total of 25 coins are used. Which of the following is the number of ₹10 coins used in the payment?",
    options: { A: "6", B: "4", C: "10", D: "8" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 10,
    text: "What is the ratio of the mean proportional of 1.21 and 0.09 with the mean proportional of 0.16 and 0.36 ?",
    options: { A: "11 : 8", B: "13 : 8", C: "13 : 12", D: "11 : 13" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 11,
    text: "The mean proportional of 8a^2 and 18/a^4 , where a is a positive number, is ____.",
    options: { A: "12/a", B: "12a", C: "12a^2", D: "12/a^2" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 12,
    text: "R pays ₹100 to P with ₹5, ₹2 and ₹1 coins. The total number of coins used for paying are 40. What is the number of coins of denomination ₹5 in the payment?",
    options: { A: "16", B: "17", C: "18", D: "13" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 13,
    text: "Find the fourth proportion of the following numbers: 4/3 rd of 27, 3/5 th of 30, 3/7 th of 35.",
    options: { A: "35", B: "40", C: "45", D: "38" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 14,
    text: "The concentration of three wines A, B and C are 10%, 20% and 30%, respectively. They are mixed in the ratio 2 : 3 : x resulting in a 23% concentration solution. Find the value of x.",
    options: { A: "7", B: "6", C: "8", D: "5" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 15,
    text: "In a school of 720 students, the ratio of boys to girls is 3 : 5. Find how many new boys may be allowed to the school if 18 new girls are admitted, so that the ratio of boys to girls changes to 2 : 3.",
    options: { A: "42", B: "50", C: "44", D: "38" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 16,
    text: "Ram has 12 hens and 5 cows, Shyam has 18 hens and 9 cows, Preetham has 4 hens and 8 cows, and Vinay has 10 hens and 7 cows. Who has a greater ratio of hens to cows?",
    options: { A: "Shyam", B: "Preetham", C: "Vinay", D: "Ram" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 17,
    text: "A company is manufacturing boxes of three types - plastic, wood and glass. The ratio of the numbers of plastic, wood and glass boxes is 2 : 3 : 5. The difference between the numbers of wood and glass boxes is 144. If the number of plastic boxes is increased by 25%, then what will be the number of plastic boxes now ?",
    options: { A: "144", B: "216", C: "360", D: "180" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 18,
    text: "Find the fourth proportional of 12/35, 3/12 and 4/12.",
    options: { A: "12 2/3", B: "3 2/4", C: "12 1/11", D: "4 2/4" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 19,
    text: "Three numbers are in the ratio 1 : 2 : 3. By adding 5 to each of the numbers then the ratio changes to 2 : 3 : 4. The smallest number is:",
    options: { A: "5", B: "15", C: "12", D: "20" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 20,
    text: "When x = 1 then y is directly proportional to x + 3 and y = 8. When z = 6 then x is inversely proportional to z and x = 2. Find the relation between y and z.",
    options: { A: "(y - 6) / z = 24", B: "(y - 6) / z = 12", C: "z(y - 6) = 12", D: "z(y - 6) = 24" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 21,
    text: "If A : B = 1/3 : 1/5, B : C = 1/7 : 1/8 and C : D = 1/10 : 1/21, then A : B : C : D is:",
    options: { A: "40 : 24 : 21 : 10", B: "48 : 23 : 25 : 8", C: "8 : 3 : 7 : 5", D: "14 : 24 : 28 : 10" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 22,
    text: "The average of the two numbers is 48. If 3 is added to a smaller number, then the ratio between them is 11 : 20. Find the larger number. (Round up to two decimal places).",
    options: { A: "40.87", B: "3.87", C: "63.87", D: "70.87" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 23,
    text: "Arrange the ratios in ascending order 5 1/3 : 3 1/4, 6 1/8 : 3 and 3.5 : 4.5.",
    options: { A: "3.5 : 4.5 < 5 1/3 : 3 1/4 < 6 1/8 : 3", B: "6 1/8 : 3 < 5 1/3 : 3 1/4 < 3.5 : 4.5", C: "5 1/3 : 3 1/4 < 3.5 : 4.5 < 6 1/8 : 3", D: "5 1/3 : 3 1/4 < 6 1/8 : 3 < 3.5 : 4.5" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 24,
    text: "The incomes of P, Q and R are in the ratio of 9 : 15 : 10 and their savings are in the ratio is 10 : 15 : 12. If R spends 60% of his income, what is the ratio of the expenditures of P, Q and R?",
    options: { A: "18 : 17 : 30", B: "17 : 30 : 18", C: "17 : 18 : 30", D: "18 : 30 : 17" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 25,
    text: "Find the fourth proportional to (a^2 - b^2) / (a^2 - ab + b^2) , (a^3 + b^3) / (a^2 + ab + b^2) , (a + b)^2 × (a^3 - b^3).",
    options: { A: "(a^2 - ab + b^2)", B: "(a + b)", C: "(a^2 + ab + b^2)", D: "(a^2 - b^2)" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 26,
    text: "Two numbers A and B are such that the sum of 6% of A and 4% of B is 2/5 of the sum of 7% of A and 11% of B, then the ratio A : B is:",
    options: { A: "3 : 7", B: "5 : 8", C: "1 : 8", D: "1 : 7" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 27,
    text: "A certain sum was to be divided between A and B in the ratio 8 : 5. However, by mistake, it was divided in the ratio 5 : 8. Thus, A gets ₹300 less than his original share. Find the sum.",
    options: { A: "₹2,600", B: "₹1,500", C: "₹1,300", D: "₹600" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 28,
    text: "When P is subtracted from each of the numbers 8, 6, 2 and 9, the numbers so obtained in this order are in proportion. What is the mean proportional between (3P - 6) and (9P - 4) ?",
    options: { A: "26", B: "28", C: "29", D: "24" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 29,
    text: "A sum of money is divided among A, B, C in the ratio 3 : 2 : 5, respectively. If the share of C is ₹300 more than B. Then how much more money will A get than B?",
    options: { A: "₹150", B: "₹75", C: "₹100", D: "₹125" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 30,
    text: "The mean proportional of (a + b)^3(a - b)^3 and (a - b)(a + b) is:",
    options: { A: "(a^2 - b^2)^2", B: "(a - b)^2(a + b)^2", C: "(a + b)^2(a - b)^2", D: "(a^2 - b^2)" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 31,
    text: "The seats for Mathematics, English and Chemistry in a school are in the ratio of 6 : 4 : 7. If these seats are increased by 20%, 40% and 60%, respectively, the ratio of the increased seats is:",
    options: { A: "9 : 7 : 8", B: "9 : 7 : 14", C: "1 : 2 : 3", D: "7 : 9 : 14" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 32,
    text: "A bag contains ₹550 in the form of 50p, 25p and 20p coins in the ratio 2 : 3 : 5. The difference between the amounts that are contributed by the 50 p and the 20 p coins is:",
    options: { A: "₹30", B: "₹20", C: "₹10", D: "₹0" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 33,
    text: "In a party hall, there are people in blue and red dresses. The ratio of the number of men in blue to the number of women in red is 3 : 7. The ratio of men in red to the number of women in blue is 2 : 1. If the ratio of the number of people in blue to the number of people in red is 35 : 76, then what is the ratio of the number of men to the number of women ?",
    options: { A: "47 : 51", B: "40 : 43", C: "62 : 57", D: "52 : 59" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 34,
    text: "P's income is 250 percent of Q's income and P's expenditure is 180 percent of Q's expenditure. If P's income is 400 percent of Q's expenditure, then what is the respective ratio of P's savings and Q's savings?",
    options: { A: "8 : 3", B: "11 : 3", C: "11 : 5", D: "5 : 2" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 35,
    text: "The number of units manufactured by company A was 12500 units in 2019 and 10625 units in 2020. While in company B, the production fell from 34000 units in 2019 to 30600 units in 2020. If X and Y are the percentage decrease in the number of units manufactured by company A and B respectively from 2019 to 2020, then what will be the ratio of X and Y?",
    options: { A: "5 : 3", B: "3 : 4", C: "3 : 2", D: "8 : 5" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 36,
    text: "In an office with 40 officers, the average salaries of class-A, class-B and class-C officers are ₹600, ₹750 and ₹1,000 a day, respectively. The number of class-A, class-B and class-C officers in the office are in the ratio 5 : 4 : 1, respectively. Find the monthly average salary (in ₹) of an officers, all the 40 of them taken together. [Assume the number of days in a month to be 30.]",
    options: { A: "25,800", B: "21,000", C: "24,030", D: "24,600" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 37,
    text: "The ratio of income of A to that of B is 4 : 3. The expenditure of A is 5/12 of his income and the expenditure of B is 7/15 of his income. The difference between their expenditure is ₹4,500. Find the income of B.",
    options: { A: "₹49,625", B: "₹48,625", C: "₹51,625", D: "₹50,625" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 38,
    text: "A sum of ₹46,800 is divided among A, B, C and D in such a way that the ratio of the combined share of A and D to the combined share of B and C is 8 : 5. The ratio of the share of B to that of C is 5: 4. A receives ₹18,400. If x is the difference between the shares of A and B and y is the difference between the shares of C and D, then what is the value of (x - y) (in ₹) ?",
    options: { A: "6000", B: "6500", C: "5000", D: "7000" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 39,
    text: "If a number of pens and pencils are bought in the ratio of 5 : 3, then Ashok has to pay ₹44. If the ratio is changed as 3 : 5, then he has to pay ₹36. Find the ratio of the price of one pen to one pencil.",
    options: { A: "5 : 3", B: "7 : 3", C: "8 : 5", D: "7 : 4" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 40,
    text: "Atul purchased Bread costing Rs.20 and gave a 100 rupee note to the shopkeeper. The shopkeeper gave the balance money in coins of denomination 2, 5, and 10. If these coins are in the ratio 5 : 4 : 1, then how many 5 coins did the shopkeeper give?",
    options: { A: "5", B: "6", C: "8", D: "4" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 41,
    text: "In a school, 3/8 of the number of students are girls and the rest are boys, One-third of the number of boys are below 10 years and 2/3 of the number of girls is also below 10 years. If the number of students of age 10 or more years is 260, then the number of boys in the school is:",
    options: { A: "280", B: "300", C: "234", D: "312" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 42,
    text: "By adding 3 and 5 in numerator and denominator of a fraction it becomes 2/3. If 1 and 3 are subtracted and added from numerator and denominator respectively, it becomes 2/5. Find the fraction.",
    options: { A: "5/7", B: "7/7", C: "7/6", D: "5/5" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 43,
    text: "A, B and C spend 80%, 85% and 75% of their incomes, respectively. If their savings are in the ratio 8 : 9 : 20 and the difference between the incomes of A and C is Rs. 18,000 , then the income of B is :",
    options: { A: "Rs. 24,000", B: "Rs. 27,000", C: "Rs. 30,000", D: "Rs. 36,000" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 44,
    text: "The ratio of income of A and B last year was 4 : 3, respectively. The ratios of their individual incomes of the last year and the present year are 3 : 4 and 5 : 6, respectively. If their total income for the present year is Rs. 8.04 lakh, then the income of B last year was :",
    options: { A: "Rs. 2.7 lakh", B: "Rs. 3.6 lakh", C: "Rs. 2.4 lakh", D: "Rs. 2.8 lakh" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 45,
    text: "The ratio of the income of A to that of B is 5 : 7. A and B save Rs. 4000 and Rs. 5000 respectively. If the expenditure of A is equal to 66 2/3 % of the expenditure of B, then the total income of A and B is :",
    options: { A: "Rs. 25,200", B: "Rs. 24,000", C: "Rs. 26,400", D: "Rs. 28,800" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 46,
    text: "The ratio between the divisor and remainder is 3 : 2 and the ratio between the divisor and the quotient is 7 : 12. If the remainder is 14, then find the remainder when the dividend is divided by 9.",
    options: { A: "3", B: "6", C: "4", D: "5" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 47,
    text: "Ravi’s age is 3/5 of Shyam’s age. After x years the ratio of the ages of Ravi and Shyam becomes 5 : 7. If initially the sum of their ages is 32, then what is the value of x ?",
    options: { A: "2", B: "4", C: "8", D: "7" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 48,
    text: "Rs. 8000 is distributed among A, B and C such that they receive notes of Rs. 500, Rs. 200 and Rs. 100 respectively. The amounts received by them are in the ratio 15 : 2 : 3. What was the ratio of the numbers of notes of Rs. 500, Rs 200 and Rs 100 ?",
    options: { A: "3:1:3", B: "3:3:1", C: "4:1:2", D: "3:2:2" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 49,
    text: "A sum of Rs. 4360 was to be divided among A , B , C and D in the ratio of 3 : 4 : 5 : 8, but it was divided in the ratio of 1/3 : 1/4 : 1/5 : 1/8 by mistake. As a result:",
    options: { A: "A received Rs. 956 more", B: "B received Rs. 318 more", C: "D received Rs. 1144 less", D: "C received Rs. 132 less" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 50,
    text: "A sum of Rs. x is divided among A , B and C such that the ratio of shares of A and B is 7 : 12 and that of B and C is 8 : 5. If the difference in the shares of A and C is Rs. 214 , then the value of x is :",
    options: { A: "11556", B: "11128", C: "11770", D: "11342" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 51,
    text: "The prices of two articles are in the ratio 4 : 5. If the price of the first article is increased by x% and that of the other is decreased by 30% , then the new prices of A and B will be in the ratio 10 : 7. The value of x is :",
    options: { A: "24.5", B: "22.5", C: "25", D: "20" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 52,
    text: "The number of red, blue, and green marbles in a bag is in the ratio 3 : 4 : 6. If 25 red marbles, 15 blue marbles, and an unknown number of green marbles are added to the bag, the ratio of red, blue, and green marbles becomes 4 : 5 : 9. Determine the number of green marbles added.",
    options: { A: "103", B: "110", C: "107", D: "105" },
    correct_answer_index: 3,
    year: "2025",
  },
  {
    question_number: 53,
    text: "The ratio of boys to girls in a school is 5 : 3. If 10 more boys join the school, the new ratio of boys to girls becomes 2:1. What is the total number of students in the school initially?",
    options: { A: "50", B: "80", C: "60", D: "100" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 54,
    text: "If 50% of A = 0.4 of B = 1/8 of C , find A : B : C",
    options: { A: "4 : 5 : 16", B: "16 : 10 : 4", C: "6 : 3 : 10", D: "10 : 4 : 16" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 55,
    text: "If B is 30% more than A, and C is 25% more than B, then what is A : C ?",
    options: { A: "13 : 8", B: "8 : 13", C: "16 : 25", D: "25 : 16" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 56,
    text: "A rope is divided in the ratio 2/3 : 4/5 : 1. Total length = 1 5/9 m. Find the smallest piece.",
    options: { A: "0.556 m", B: "0.889m", C: "1.333m", D: "2.222m" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 57,
    text: "If M : N = 3 : 4, N : O = 5 : 6, and O : P = 8 : 10, then find N : P .",
    options: { A: "5 : 7", B: "2 : 3", C: "4 : 5", D: "3 : 2" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 58,
    text: "What should be subtracted from 52, 47, 20, 19 so that the remaining numbers may be proportional ?",
    options: { A: "3", B: "9", C: "4", D: "12" },
    correct_answer_index: 3,
    year: "2025",
  },
  {
    question_number: 59,
    text: "The number of red, blue, and green balls in a bag is in the ratio 2: 3: 5. If 10 red balls , 10 blue balls, and an unknown number of green balls are added to the bag, the ratio of red, blue, and green balls becomes 3 : 4 : 6. Determine the number of green balls added.",
    options: { A: "3", B: "6", C: "7", D: "10" },
    correct_answer_index: 3,
    year: "2025",
  },
  {
    question_number: 60,
    text: "If P : Q = 7 : 5, Q : R = 2 : 3, and R : S = 4 : 5, find the ratio P : S.",
    options: { A: "28 : 25", B: "56 : 75", C: "30 : 25", D: "70 : 56" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 61,
    text: "If x : y = 2 : 5, then find (3x + 2y) : (7x − 2y).",
    options: { A: "3 : 2", B: "4 : 1", C: "7 : 4", D: "9 : 5" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 62,
    text: "A ₹48,000 annual bonus is distributed among Sales, Marketing, and Operations in a 5 : 4 : 3 ratio. Marketing uses ₹3,000 for team building and ₹1,500 for an intern, then allocates the rest to two top performers in a 3 : 2 ratio. How much does the top performer with the smaller share receive ?",
    options: { A: "₹5,833.33", B: "₹5,250", C: "₹4,600", D: "₹4,200" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 63,
    text: "If A : B = 4 : 7, B : C = 3 : 5, and C : D = 8 : 9, find A : B : C : D.",
    options: { A: "96 : 168 : 280 : 315", B: "168 : 96 : 280 : 315", C: "96 : 168 : 315 : 280", D: "96 : 280 : 168 : 315" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 64,
    text: "A box contains ₹10, ₹5, and ₹2 coins in the ratio 1 : 2 : 3. If the total amount of money in the box is ₹416 , find the number of coins of each kind.",
    options: { A: "20 coins of ₹10, 40 of ₹5, and 60 of ₹2", B: "16 coins of ₹10, 32 of ₹5, and 48 of ₹2", C: "10 coins of ₹10, 20of ₹5, and 30 of ₹2", D: "16 coins of ₹10, 32 of ₹5, and 46 of ₹2" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 65,
    text: "If a : b = 5 : 6, find (3a + 4b) : (3a - 4b).",
    options: { A: "9 : 1", B: "1 : 9", C: "7 : 1", D: "1 : 7" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 66,
    text: "If 20% of a is equal to 15% of b, then find the ratio a : b.",
    options: { A: "6 : 5", B: "3 : 4", C: "2 : 5", D: "5 : 4" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 67,
    text: "What should be subtracted from 5, 8, 7, 12 so that the remaining numbers may be proportional ?",
    options: { A: "2", B: "3", C: "4", D: "5" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 68,
    text: "Given that W : X = 3 : 5, X : Y = 5 : 7, and Y : Z = 7 : 9, find the compound ratio W : X : Y : Z.",
    options: { A: "20 : 24 : 56 : 63", B: "3 : 5 : 7 : 9", C: "5 : 6 : 14 : 9", D: "20 : 24 : 42 : 63" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 69,
    text: "If 40% of (P + Q) = 60% of (P – Q), then find the ratio P: Q .",
    options: { A: "5 : 1", B: "2 : 3", C: "2 : 5", D: "3 : 2" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 70,
    text: "If P is 25% more than Q, and Q is 20% more than R, then what is P : R ?",
    options: { A: "3 : 2", B: "4 : 3", C: "7 : 4", D: "3 : 4" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 71,
    text: "If 20% of (A + B) = 60% of (A - B), then find the ratio A: B.",
    options: { A: "1 : 2", B: "2 : 1", C: "1 : 3", D: "3 : 1" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 72,
    text: "If 44% of P is equal to 24% of Q, what is the ratio P : Q ?",
    options: { A: "6 : 11", B: "6 : 13", C: "13 : 7", D: "11 : 6" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 73,
    text: "If 20% of A = 0.5 of B = 1/4 of C, then what is A : B : C ?",
    options: { A: "5 : 2 : 4", B: "5 : 4 : 2", C: "5 : 4 : 8", D: "5 : 3 : 2" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 74,
    text: "If 75% of P = 60% of Q = 30% of R, find P : Q : R.",
    options: { A: "4 : 5 : 10", B: "10 : 5 : 4", C: "5 : 4 : 10", D: "2 : 3 : 5" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 75,
    text: "If 37.5% of p is equal to 25% of q, what is the ratio p : q ?",
    options: { A: "1 : 4", B: "4 : 1", C: "3 : 2", D: "2 : 3" },
    correct_answer_index: 3,
    year: "2025",
  },
  {
    question_number: 76,
    text: "If (A + B) : (A - B) = 7 : 3, find (A³ + B³) : (A³ - B³)",
    options: { A: "195 : 148", B: "125 : 137", C: "133 : 117", D: "123 : 117" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 77,
    text: "A wire is cut into three pieces in the ratio 3 : 4 : 8. If the length of the longest piece is 40 cm, what is the total length of the wire ?",
    options: { A: "40 cm", B: "50 cm", C: "75 cm", D: "85 cm" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 78,
    text: "Three friends share a winning prize in the ratio 3 : 4 : 5. If the total prize is Rs. 15000, how much more does the person with the highest share get than the lowest ?",
    options: { A: "3500", B: "3000", C: "2500", D: "1250" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 79,
    text: "Two numbers are in the ratio 3 : 5. If the difference between them is 16, find the numbers.",
    options: { A: "24 and 40", B: "18 and 35", C: "15 and 35", D: "18 and 25" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 80,
    text: "The weights of three friends are in the ratio 4: 5 : 6. If each gains 9 kg, the new ratio becomes 13 : 14 : 15. What is the original weight of the heaviest friend?",
    options: { A: "5 kg", B: "7 kg", C: "6 kg", D: "9 kg" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 81,
    text: "If x : y = 3 : 7, then what is (2x + 3y) : (x + y) ?",
    options: { A: "27 : 10", B: "7 : 19", C: "16 : 7", D: "7 : 16" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 82,
    text: "A 30-liter solution contains acid and water in the ratio 2 : 1. How much water must be added to make the ratio 1 : 1?",
    options: { A: "11 L", B: "10 L", C: "12 L", D: "21 L" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 83,
    text: "P and Q share profit in 9 : 7. If P gets Rs. 27,000, how much did Q receive?",
    options: { A: "Rs. 21,500", B: "Rs. 10,000", C: "Rs. 21,000", D: "Rs. 22,000" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 84,
    text: "P : Q = 2 : 3, Q : R = 6 : 5, R : S = 10 : 7. What is the ratio P : S ?",
    options: { A: "8 : 7", B: "5 : 6", C: "11 : 13", D: "7 : 8" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 85,
    text: "A box has 120 pencils in red, blue, and black in the ratio 3:2:5. If 10 red and 20 black pencils are removed, what is the new ratio of red to black pencils?",
    options: { A: "1 : 2", B: "3 : 5", C: "13 : 15", D: "13 : 20" },
    correct_answer_index: 3,
    year: "2025",
  },
  {
    question_number: 86,
    text: "If 50% of A = 1/6 of B = 1/4 of C , find A : B : C",
    options: { A: "1 : 2 : 3", B: "11 : 12 : 13", C: "6 : 4 : 5", D: "7 : 4 : 8" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 87,
    text: "The weights of three friends are in the ratio 8 : 7 : 3. If each gains 9 kg, the new ratio becomes 17 : 16 : 12. What is the original weight of the heaviest friend?",
    options: { A: "4 kg", B: "8 kg", C: "10 kg", D: "7 kg" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 88,
    text: "If a number x is subtracted from 52, 47, 20, and 19, the resulting numbers are in proportion. What is the value of x + 5 ?",
    options: { A: "13", B: "19", C: "17", D: "12" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 89,
    text: "A stationery shop ordered 16 dozen black pens and some additional dozen blue pens. The price of the black pens per dozen was two times that of the blue ones. When the order was delivered, it was found that the number of dozens of the two colours had been interchanged. This increased the bill by 50%. Find the ratio of the number of dozens of black pens to the number of dozens of blue pens in the original order.",
    options: { A: "1 : 4", B: "1 : 2", C: "2 : 3", D: "3 : 4" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 90,
    text: "If 75% of P = 60% of Q = 30% of R, find P : Q : R.",
    options: { A: "4 : 5 : 10", B: "10 : 5 : 4", C: "5 : 4 : 10", D: "2 : 3 : 5" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 91,
    text: "In a village, there are 3,200 females for every 4,000 males. What is the sex ratio in this city (number of females per 1000 males) ?",
    options: { A: "700", B: "750", C: "820", D: "800" },
    correct_answer_index: 3,
    year: "2025",
  },
  {
    question_number: 92,
    text: "A jar contains marbles in the ratio 4 : 6 : 5 (red : green : blue). If there are 150 marbles in total, how many are green?",
    options: { A: "40", B: "45", C: "60", D: "75" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 93,
    text: "Jupiter and Saturn take 9 hours 50 minutes and 11 hours 40 minutes respectively to complete one rotation. What is the ratio of their rotation times in the lowest form?",
    options: { A: "59 : 70", B: "49 : 58", C: "59 : 69", D: "50 : 68" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 94,
    text: "Rahim earns ₹16,000 per month, and Ami earns ₹2,04,000 per annum. If both spend ₹12,000 per month, what is the ratio of their savings?",
    options: { A: "1 : 2", B: "2 : 3", C: "1 : 3", D: "4 : 5" },
    correct_answer_index: 3,
    year: "2025",
  },
  {
    question_number: 95,
    text: "What is the mean proportional between 9 and 25 ?",
    options: { A: "12", B: "13", C: "15", D: "20" },
    correct_answer_index: 2,
    year: "2025",
  },
  {
    question_number: 96,
    text: "If the ratio is 21 : 3 = 7 : y . Then find the y.",
    options: { A: "7", B: "4", C: "5", D: "1" },
    correct_answer_index: 3,
    year: "2025",
  },
  {
    question_number: 97,
    text: "If 10, 15, x are in proportion. Find the value of x.",
    options: { A: "22.5", B: "25", C: "30", D: "45" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 98,
    text: "On a certain assembly line the rejection rate for Maruti Alto production was 5 percent for Maruti Swift production 9 percent and the two cars combined 8 percent. What was the ratio of Maruti Swift production to Maruti Alto production?",
    options: { A: "3 : 2", B: "3 : 1", C: "5 : 3", D: "7 : 2" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 99,
    text: "In a school’s sports department, the ratio of the number of boys to girls is 7 : 4. If there are 196 girls, the total number of students in the sport’s department is:",
    options: { A: "420", B: "539", C: "512", D: "490" },
    correct_answer_index: 1,
    year: "2025",
  },
  {
    question_number: 100,
    text: "Aman collection contains Spain, Japan, and France stamps. If the ratio of Spain to Japan stamps is 3 to 4 and the ratio of Japan to France stamps is 6 to 5, what is the ratio of Spain to France stamps ?",
    options: { A: "9 : 10", B: "5 : 4", C: "3 : 5", D: "18 : 5" },
    correct_answer_index: 0,
    year: "2025",
  },
  {
    question_number: 101,
    text: "A sum of Rs. 630 is to be divided among A, B and C such that 3 times A's share, 6 times B's share and 5 times C's share are all equal. The share of C is:",
    options: { A: "Rs. 150", B: "Rs. 180", C: "Rs. 200", D: "Rs. 225" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 102,
    text: "A recipe uses flour and cocoa powder in the ratio 5 : 2. If you have 500 grams of flour, how much cocoa powder do you need to keep the same ratio?",
    options: { A: "150", B: "180", C: "200", D: "250" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 103,
    text: "The present ratio of students to teachers at a certain college is 40 : 1. If the student enrollment were to increase by 60 students and the number of teachers were to increase by 4, the ratio of the teachers would then be 30 : 1. What is the present number of teachers?",
    options: { A: "6", B: "5", C: "8", D: "10" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 104,
    text: "If the ratio is 36 : 8 = 9x : 16. Then find the x.",
    options: { A: "6", B: "7", C: "8", D: "9" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 105,
    text: "Two numbers are in ratio 3 : 7. If the sum is 80, find the numbers.",
    options: { A: "24:56", B: "27:53", C: "21:56", D: "38:42" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 106,
    text: "In a factory, the ratio of skilled to unskilled workers was 8 : 5 . After a recruitment drive, the number of skilled workers increased by 15% , while the number of unskilled workers increased by 20% . What is the new ratio of skilled to unskilled workers?",
    options: { A: "21 : 12", B: "23 : 15", C: "8 : 5", D: "21 : 25" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 107,
    text: "Find the fourth proportional to 32 , 48, and 64.",
    options: { A: "84", B: "96", C: "48", D: "60" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 108,
    text: "The ratio of the number of boys to the number of girls in a class is 10 : 13. If there are 115 students in the class, how many boys are there?",
    options: { A: "50", B: "75", C: "85", D: "60" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 109,
    text: "The ratio of the ages of two friends is 5 : 6. After 15 years, the ratio becomes 8 : 9. What are their present ages?",
    options: { A: "20 and 30", B: "52 and 58", C: "25 and 30", D: "24 and 28" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 110,
    text: "Three people P, Q, and R, have incomes that are in the ratio 13 : 14 : 15. If their total earnings are Rs. 2,31,000, how much money does Q earn?",
    options: { A: "Rs. 91,000", B: "Rs. 93,500", C: "Rs. 1,04,500", D: "Rs. 77,000" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 111,
    text: "If a man's age is four times the sum of the ages of his three children, and after 6 years his age will be twice the sum of the ages of his three children, then what is the man's present age?",
    options: { A: "60 years", B: "56 years", C: "45 years", D: "30 years" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 112,
    text: "In a student council election, there were three contestants. All the voters participated in the voting and 10% of votes were declared invalid. The contestants got the votes in the ratio 8 : 7 : 5. If the second candidate in the list got 4725 votes, the total number of valid votes is:",
    options: { A: "10,000", B: "11,500", C: "13,500", D: "9,000" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 113,
    text: "141 is divided into two parts in such a way that the one-eighth part of the first and one-ninth part of the second are in the ratio 5 : 6. Find the first part.",
    options: { A: "36", B: "72", C: "48", D: "60" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 114,
    text: "The salaries of A and B are in a ratio of 2 : 3. Their savings are equal. If A's expenditure is 1/2 of the salary, then what per cent of income does B spends ?",
    options: { A: "66.67%", B: "78.5%", C: "50%", D: "75%" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 115,
    text: "360 toffees are distributed among Pushkal, Quadir and Rustam in the ratio 2 : 3 : 4. After distribution, Quadir gives 20% of his toffees to Pushkal and Rustam gives 25% of his toffees to Pushkal. What is the new ratio of toffees with Pushkal, Quadir and Rustam ?",
    options: { A: "5 : 4 : 6", B: "7 : 3 : 5", C: "6 : 4 : 5", D: "3 : 5 : 7" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 116,
    text: "Due to a fault in the voting machine, the invalid votes are counted in votes of the candidate B, who gets 5 times the invalid votes. A gets 8 times the invalid votes and wins the election by 28. What is the total number of votes polled ?",
    options: { A: "168", B: "184", C: "196", D: "176" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 117,
    text: "The mean proportional between the numbers p and q is 8. Which of the following pairs of numbers can be the values of p and q ?",
    options: { A: "12 and 3", B: "16 and 4", C: "12 and 16", D: "10 and 6" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 118,
    text: "The ratio of the incomes of Rama and Ganga is 4 : 3 and the ratio of their expenditures is 3 : 2. If each person saves ₹2,700, then find their expenditures, respectively.",
    options: { A: "₹8,100 and ₹5,000", B: "₹8,000 and ₹5,000", C: "₹8,100 and ₹5,400", D: "₹8,000 and ₹5,400" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 119,
    text: "Shankar comes to buy a T-shirt in a showroom. He purchases a shirt which costs ₹1,020 after a discount. He pays his bill in the form of 50 paise, 20 paise and 10 paise coins in the ratio 2 : 3 : 4 (assume for the sake of the problem). What is the number of 10 paise coins he used to pay his bill ?",
    options: { A: "1530", B: "510", C: "1020", D: "2040" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 120,
    text: "What should be added to each of the four numbers 5, 19, 7 and 25 to make them proportional ?",
    options: { A: "2", B: "3", C: "1", D: "4" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 121,
    text: "If 49 : x :: x : 81 and 64 : y :: y : 169, where x and y are both natural numbers, then find the value of 2x + 3y.",
    options: { A: "312", B: "126", C: "348", D: "438" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 122,
    text: "When x is added to each of 2, 3, 30 and 35, then the numbers obtained in this order are in proportion. What is the second largest part in the proportion ?",
    options: { A: "40", B: "30", C: "35", D: "45" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 123,
    text: "The quantity of milk ordered on the first, second, third and fourth day of a four day ceremony is in the proportion of 30 litres, 24 litres, 35 litres and ‘x’ litres, respectively. Find the quantity of milk (in litres) ordered on the fourth day.",
    options: { A: "30", B: "32", C: "28", D: "26" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 124,
    text: "The average marks (out of 100) of boys and girls in an examination are 75 and 80, respectively. If the average marks of all the students in that examination are 78. Find the ratio of the number of boys to the number of girls.",
    options: { A: "2 : 3", B: "3 : 4", C: "1 : 3", D: "1 : 2" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 125,
    text: "At present, A is thrice as old as B. C is 5 years elder than B. The sum of the ages of A, B, C is 75 years. The ratio of the age of B five years ago to the age of A three years from now is:",
    options: { A: "2 : 3", B: "1 : 4", C: "4 : 7", D: "1 : 5" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 126,
    text: "If x varies inversely as y^2 and x = 2 when y = 6, then the value of x when y = 3 is:",
    options: { A: "2", B: "3", C: "4", D: "6" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 127,
    text: "The ages of two friends, Ram and Ravi, differ by 7 years. Ram’s mother Mayadevi is three times as old as Ram, and Ravi is four times as old as his brother Soham. The ages of Mayadevi and Soham differ by 65 years. Find the age of Mayadevi (in years).",
    options: { A: "69", B: "36", C: "85", D: "45" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 128,
    text: "What is the value of D, if A : C = B : D in the given table? A = 25, B = 40, C = 30, D = ?",
    options: { A: "56", B: "48", C: "45", D: "42" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 129,
    text: "A money bag contains one rupee, 5 rupee and 10 rupee coins in the ratio of 3 : 5 : 7 respectively. If the total amount in the bag is ₹980, then find the number of coins of ₹10.",
    options: { A: "69", B: "70", C: "71", D: "68" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 130,
    text: "A sum of money is divided among P, Q, R and S in the proportion of 4 : 9 : 2 : 3. If Q gets ₹560 more than R, then the share of S is:",
    options: { A: "₹140", B: "₹340", C: "₹240", D: "₹440" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 131,
    text: "The incomes of P, Q and R are in the ratio 10 : 12 : 9 and their expenditures are in the ratio 12 : 15 : 8. If Q saves 25% of his income, then what is the ratio of the savings of P, Q and R ?",
    options: { A: "15 : 14 : 21", B: "14 : 15 : 21", C: "21 : 15 : 14", D: "21 : 14 : 15" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 132,
    text: "Raj divides ₹1,200 in the ratio 2 : 1 : 3 among three of his friends. The amount equal to the sum of three times the largest share and two times the smallest share is:",
    options: { A: "₹2,400", B: "₹1,800", C: "₹2,200", D: "₹2,000" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 133,
    text: "The ratio between male and female members in a club is 2 : 3. If the number of male members is increased by 200, the ratio becomes 5 : 6. How many female members are there in the club?",
    options: { A: "1200", B: "900", C: "1400", D: "1000" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 134,
    text: "Find the mean proportional of 12.96 and 0.16.",
    options: { A: "1.21", B: "1.96", C: "1.44", D: "1.69" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 135,
    text: "In a collection of rare coins, there is one gold coin for every four non-gold coins. If 20 more gold coins are added to the collection, the ratio of the number of gold coins to that of non-gold coins will be 2:3. The total number of coins in the collection will now become ________.",
    options: { A: "80", B: "60", C: "100", D: "48" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 136,
    text: "In a company, the ratio of men and women is 5 : 3, respectively. When 150 additional women are employed in the company, the ratio becomes 5 : 4. How many men are employed in the company?",
    options: { A: "850", B: "750", C: "550", D: "950" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 137,
    text: "There are y yellow marbles and b blue marbles in a box. 18% of the yellow marbles were added to 24% of the blue marbles, and the total was 30. Three times the number of yellow marbles exceeds two times the number of blue marbles by 200. What is the ratio of y^2 to b^2 ?",
    options: { A: "6 : 5", B: "4 : 1", C: "2 : 1", D: "5 : 2" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 138,
    text: "The mean proportional of 4a^2 and x is a/5, where a is a positive number, then the value of x is ______",
    options: { A: "1 / 100a^4", B: "1 / 100a^2", C: "1 / 25a^2", D: "1 / 25a^4" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 139,
    text: "The cost of a diamond varies directly as the square of its weight. Once, this diamond broke into four pieces with weights in the ratio of 4 : 3 : 2 : 1 .When the pieces were sold, the merchant got ₹63,000 less than that of one piece. Find the original price of the diamond.",
    options: { A: "₹86,000", B: "₹80,000", C: "₹90,000", D: "₹75,000" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 140,
    text: "The ratio of boys to girls initial in a college is 5 : 6. If 40 boys leave the college and 50 girls join the college, the ratio will become 8 : 11. Find the number of girls (initial) in the college.",
    options: { A: "740", B: "860", C: "720", D: "640" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 141,
    text: "30 is the mean proportional of 18 and A. Find the value of A.",
    options: { A: "60", B: "40", C: "45", D: "50" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 142,
    text: "The salaries of P and Q together amount to ₹9,60,000. P and Q save 64% and 44%, respectively of their individual salaries. If P’s expenditure is 1.5 times Q’s expenditure, then what is the ratio of P’s salary to Q’s salary?",
    options: { A: "2 : 3", B: "7 : 3", C: "3 : 7", D: "3 : 2" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 143,
    text: "The ratio of circumference and diameter of a circle is 3 : 5. If the circumference is 6 cm, then the radius of the circle is:",
    options: { A: "10 cm", B: "15 cm", C: "5 cm", D: "1.8 cm" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 144,
    text: "If a : b = c : d = e : f = 5 : 7, then what is the ratio (3a + 5c + 11e) : (3b + 5d + 11f)?",
    options: { A: "7 : 11", B: "3 : 7", C: "5 : 7", D: "11 : 7" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 145,
    text: "The monthly incomes of A, B and C are in the ratio 2 : 9 : 3 and their expenses are in the ratio 3 : 9 : 5. If A's saving is half of his total income, then savings of A, B and C are, respectively, in the ratio of:",
    options: { A: "3 : 9 : 2", B: "2 : 5 : 2", C: "3 : 18 : 4", D: "1 : 2 : 1" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 146,
    text: "Radhika requested the cashier of a bank to get her coins in lieu of her cheque worth ₹1,845. Cashier gave her a packet containing ₹5, ₹10 and ₹20 coins in the ratio of 3 : 5 : 7. What is the total worth of the smallest coin received by her ?",
    options: { A: "₹135", B: "₹125", C: "₹145", D: "₹105" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 147,
    text: "The age of the older of two boys is thrice that of the younger. 9 years ago it was five times that of the younger. Find the present age of each.",
    options: { A: "15 years, 45 years", B: "18 years, 54 years", C: "17 years, 51 years", D: "12 years, 36 years" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 148,
    text: "P pays Q a sum of ₹150 using coins of ₹2, ₹5 and ₹10. He uses a total of 50 coins. If the ratio of ₹2 and ₹5 coins used is 5 : 2, then how many coins of ₹10 are used in the payment?",
    options: { A: "2", B: "1", C: "4", D: "5" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 149,
    text: "In what ratio must a grocer mix two varieties of pulses costing ₹60 and ₹75 per kg, respectively, so as to get a mixture worth ₹65 per kg ?",
    options: { A: "3 : 4", B: "2 : 1", C: "2 : 3", D: "1 : 2" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 150,
    text: "M varies inversely as (N^2 + 3). If M = 3 when N = 3, then what will be the value of M when N^2 = 69 ?",
    options: { A: "1", B: "1/4", C: "1/69", D: "1/2" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 151,
    text: "The difference between two numbers is 48. The ratio of these two numbers is 7 : 3. What is the sum of the two numbers ?",
    options: { A: "110", B: "100", C: "90", D: "120" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 152,
    text: "Divide some money in the ratio Ravi, Reeta and Rahul that 5 (Part of Ravi) = 3 (Part of Reeta) = 11 (Part of Rahul). The money ratio of Ravi : Reeta : Rahul is equal to :",
    options: { A: "11 : 5 : 3", B: "11 : 33 : 15", C: "5 : 11 : 3", D: "33 : 55 : 15" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 153,
    text: "Among the ratios 3 : 4, 5 : 8, 1 : 2, 6 : 9 which is the greatest?",
    options: { A: "5 : 8", B: "6 : 9", C: "1 : 2", D: "3 : 4" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 154,
    text: "If a : b = 3 : 7 and b : c = 4 : 9, then find a : b : c.",
    options: { A: "12 : 28 : 63", B: "3 : 28 : 63", C: "12 : 28 : 9", D: "3 : 28 : 9" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 155,
    text: "Which is the greatest ratio among the following? 4/5 , 1/11 , 1/2 , and 8/11",
    options: { A: "4/5", B: "1/11", C: "1/2", D: "8/11" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 156,
    text: "When ‘X’ is added to each of the numbers 7, 11, 18 and 23, then the number so obtained are in proportion. What is the mean proportional between the (x - 1) and (2x - 10) ?",
    options: { A: "78", B: "98", C: "48", D: "68" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 157,
    text: "Convert 28% into the form of ratio.",
    options: { A: "25 : 7", B: "7 : 25", C: "7 : 18", D: "18 : 7" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 158,
    text: "A box filled with gift articles weighs 25 kg. If the weight of the box and the gift articles, respectively, are in the ratio 1 : 9, then the weight of the articles (in grams) is:",
    options: { A: "22500", B: "23500", C: "21500", D: "24500" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 159,
    text: "Find the third proportion to 36 and 48.",
    options: { A: "36", B: "54", C: "48", D: "64" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 160,
    text: "If a : b = 3 : 4, b : c = 2 : 3, and c : d = 5 : 6, then a : b : c : d is:",
    options: { A: "10 : 20 : 30 : 36", B: "15 : 25 : 30 : 36", C: "15 : 20 : 30 : 36", D: "15 : 20 : 35 : 36" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 161,
    text: "If 1/M : 1/N : 1/O = 3 : 4 : 5, then M : N : O is equal to :",
    options: { A: "12 : 15 : 20", B: "20 : 15 : 12", C: "20 : 12 : 15", D: "15 : 20 : 12" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 162,
    text: "The mean proportion of 0.14 and 2.24 is:",
    options: { A: "0.56", B: "- 2.39", C: "1.12", D: "1.02" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 163,
    text: "Find the fourth proportion to 1.25, 5.75 and 3.5",
    options: { A: "4.5", B: "16.1", C: "12.5", D: "6.5" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 164,
    text: "Two numbers are in the ratio 2 : 3. Their sum is 135. Find the numbers.",
    options: { A: "54, 81", B: "45, 90", C: "50, 85", D: "60, 75" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 165,
    text: "Find the mean proportional between 25 and 81.",
    options: { A: "12", B: "36", C: "81", D: "45" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 166,
    text: "Two numbers are, respectively, 30% and 60% more than a third number. The ratio of the two numbers is:",
    options: { A: "13 : 16", B: "12 : 13", C: "11 : 15", D: "13 : 17" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 167,
    text: "The strength of a school is 640, with the number of boys being 400. Find the ratio of girls to boys.",
    options: { A: "5 : 6", B: "3 : 5", C: "4 : 5", D: "8 : 5" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 168,
    text: "Raju and Ramu have more land than Sonu by 15% and 25%, respectively. What is the ratio of land owned by Raju and Ramu?",
    options: { A: "56 : 25", B: "21 : 23", C: "23 : 25", D: "25 : 23" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 169,
    text: "If x : y = 5 : 6,then 2x + 3y : 3x + 5y is:",
    options: { A: "18 : 35", B: "28 : 45", C: "18 : 45", D: "28 : 48" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 170,
    text: "Which of the following ratios is greater ?",
    options: { A: "7 : 4", B: "8 : 3", C: "2 : 3", D: "1 : 5" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 171,
    text: "The ratio of red to green sweets in a bag is 3 : 4. How many red sweets are there in the bag if the number of green sweets is 120 ?",
    options: { A: "80", B: "100", C: "70", D: "90" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 172,
    text: "Find the mean proportion to 0.72 and 2.85 (round up to one decimal place).",
    options: { A: "1.4", B: "0.7", C: "2.8", D: "0.4" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 173,
    text: "What should be added to each term of the ratio 5 : 11 so that the ratio becomes 3 : 5 ?",
    options: { A: "5", B: "4", C: "2", D: "6" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 174,
    text: "Two numbers are in the ratio of 3 : 7. If 11 is subtracted from each, the ratio between the numbers becomes 7 : 20. Find the smaller number.",
    options: { A: "39", B: "21", C: "36", D: "27" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 175,
    text: "If 40% of A = 60% of B = 1/6 of C, then find the ratio of A : B : C.",
    options: { A: "15:10:18", B: "36:10:15", C: "15:10:36", D: "10:15:36" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 176,
    text: "The ratio of marks of A and B is 3 : 4 and the ratio of marks of B and C is 4 : 5. If the difference in the marks of C and A is 30, then how much marks does B get?",
    options: { A: "52", B: "64", C: "60", D: "56" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 177,
    text: "A sum of ₹17,600 was divided between Jeevan, Praveen and Kanan, such that the ratio of the sums received by Jeevan and Praveen was 5 : 8, while the ratio of the sums received by Praveen and Kanan was 3 : 2. How much money did Jeevan receive as his share?",
    options: { A: "₹4,900", B: "₹4,750", C: "₹4,850", D: "₹4,800" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 178,
    text: "Find the natural number obtained when the number 13 is subtracted from the mean proportional of 75 and 12.",
    options: { A: "14", B: "30", C: "27", D: "17" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 179,
    text: "If four distinct positive numbers, a, b, c and d, in the order given are in proportion, then which of the following options is NOT correct?",
    options: { A: "b, a, d and c, in the order given are in proportion.", B: "c, d, b and a, in the order given are in proportion.", C: "d, c, b and a, in the order given are in proportion.", D: "a, c, b and d, in the order given are in proportion." },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 180,
    text: "Let 'a' be a positive number and b. What is the mean proportional of a^4/b and b^3/a^2 ?",
    options: { A: "4", B: "3", C: "2", D: "a" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 181,
    text: "What is the ratio between S and T if S is 75% of T ?",
    options: { A: "4 : 3", B: "2 : 3", C: "75 : 1", D: "3 : 4" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 182,
    text: "In a school, the total number of boys is 20% more than the total number of girls. What is the ratio of the number of boys to that of girls in the school ?",
    options: { A: "6 : 5", B: "5 : 6", C: "5 : 3", D: "4 : 5" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 183,
    text: "42% of Ranita’s weekly income is equal to 56% of Bhaskar’s weekly income. If Bhaskar’s weekly income was raised by ₹ 200, while Ranita’s weekly income did not change, the ratio of the weekly incomes of Ranita and Bhaskar, respectively, would have been 5 : 4. What is Ranita’s weekly income (in ₹) ?",
    options: { A: "4200", B: "3600", C: "3000", D: "4000" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 184,
    text: "Swati earns a sum of ₹40,000, out of which she saves 25%. She spends the remaining amount on food and education in the ratio of 3 : 2. What is the percentage of expenditure incurred on education to her total income?",
    options: { A: "30%", B: "20%", C: "60%", D: "40%" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 185,
    text: "In an educational institution, the ratio of the numbers of students in middle school and in high school, respectively, in a given year was given as 4 : 3. If there were 324 students in middle school in that year in that institution, what was the number of students in high school in the same year in that institution?",
    options: { A: "243", B: "240", C: "249", D: "246" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 186,
    text: "If class A has 11 boys and 18 girls, class B has 13 boys and 17 girls, and class C has 20 boys and 9 girls, which class has the biggest ratio(s) of boys to girls?",
    options: { A: "Class A", B: "Both class A and class B", C: "Class C", D: "Class B" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 187,
    text: "A recipe is made using cheese and butter in the ratio 4: 3. If Arohi uses 8 bowls of cheese, how many bowls of butter should she use?",
    options: { A: "4", B: "6", C: "8", D: "3" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 188,
    text: "The ratio of the salaries of S to F is 2 : 3 and the ratio of their savings is 3 : 4. What is the ratio of their expenditures if their total savings are equal to the salary of S?",
    options: { A: "8 : 15", B: "7 : 15", C: "8 : 13", D: "7 : 12" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 189,
    text: "S varies directly as (R + 7), and S = 42 when R = 17. What is the value of S when R = 29 ?",
    options: { A: "51", B: "63", C: "58", D: "66" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 190,
    text: "The price of a television set and a washing machine are in the ratio of 8 : 7. If the cost of the television set is ₹4,800 more than the cost of the washing machine, then find the price of the washing machine.",
    options: { A: "₹33,000", B: "₹33,500", C: "₹33,600", D: "₹33,700" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 191,
    text: "Pooja, Chameli and Anju have a total of ₹450 in their purses. Pooja has ₹50 more than Chameli. Anju has two times what Pooja has. How much do Pooja, Chameli and Anju, respectively, have in their purses ?",
    options: { A: "₹150, ₹75 and ₹225", B: "₹100, ₹50 and ₹300", C: "₹125, ₹75 and ₹250", D: "₹125, ₹50 and ₹275" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 192,
    text: "Two numbers are in the ratio 4 : 5. If 3 is added to the smaller and 7 is subtracted from the larger number, they are in the ratio 1 : 1. Find the numbers.",
    options: { A: "60, 75", B: "40, 50", C: "55, 44", D: "20, 25" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 193,
    text: "What is the mean proportional of 45x^4 and 5y^2 ?",
    options: { A: "5x^2y", B: "25x^4y", C: "15x^2y", D: "45x^2y^2" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 194,
    text: "The ages of A and B are in the ratio 4 : 7, respectively. After 8 years, the ratio of their ages will be 2 : 3. What is the sum of the ages of A and B (in years)?",
    options: { A: "44", B: "36", C: "38", D: "42" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 195,
    text: "Which number should be added to 3, 11, 4 and 14 to make them in proportion?",
    options: { A: "3", B: "2", C: "4", D: "1" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 196,
    text: "Two numbers are in the ratio 4 : 5. If 17 is subtracted from each, the new numbers are in the ratio 11 : 14. If 20 is added to each of the original numbers, then the ratio becomes:",
    options: { A: "224 : 275", B: "275 : 241", C: "241 : 275", D: "224 : 241" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 197,
    text: "A bag contains a total of 180 coins in the denominations of ₹5 and ₹1. Find the number of ₹5 coins in the bag, if the total value of the coins is ₹500.",
    options: { A: "60", B: "120", C: "80", D: "100" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 198,
    text: "Find the third proportional of 9, 7, ?, 14.",
    options: { A: "21", B: "16", C: "24", D: "18" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 199,
    text: "Find the ratio between the fourth proportional of 42, 56, 63 and the fourth proportional of 189, 273, and 153.",
    options: { A: "33 : 221", B: "217 : 42", C: "33 : 84", D: "84 : 221" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 200,
    text: "Rishi and Sarita have ₹4,760. If 3/16 of Rishi's amount is equal to 9/4 of Sarita's amount, how much does Sarita have?",
    options: { A: "₹3,570", B: "₹1,190", C: "₹2,720", D: "₹2,040" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 201,
    text: "A sum of money was divided between Cyrus, Rohan and Mishti. The ratio of the sums received by Cyrus and Rohan was 3 : 2, while the ratio of the sums received by Rohan and Mishti was 7 : 12. If the sum received by Cyrus was ₹1,800 less than the sum received by Mishti, how many rupees did Rohan receive as his share?",
    options: { A: "₹9,240", B: "₹7,560", C: "₹8,400", D: "₹6,300" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 202,
    text: "The third proportional to (5^2 - 3^2) and (5 - 3) is:",
    options: { A: "1/3", B: "1/8", C: "1/2", D: "1/4" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 203,
    text: "Four distinct positive numbers, ‘a’, ‘b’, ‘c’ and ‘d’, in the order given, are in proportion. ‘b’ is 35 more than ‘a’ and ‘d’ is 60 more than ‘c’. The product of ‘a’ and ‘c’ is 5376. What is the sum of ‘a’, ‘b’, ‘c’ and ‘d’?",
    options: { A: "398", B: "400", C: "399", D: "397" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 204,
    text: "A bag contains rupee, 50-paise and 25-paise coins in the ratio 3 : 4 : 6. If the total amount is ₹143, the number of 50-paise coins is:",
    options: { A: "132", B: "66", C: "90", D: "88" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 205,
    text: "The sum of the four numbers A, B, C and D is 875. If the ratio of A to B is 1 : 2, the ratio of B to C is 3 : 1 and the ratio of C to D is 2 : 3, find the value of C.",
    options: { A: "120", B: "130", C: "125", D: "135" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 206,
    text: "The ratio of the expenditure to the savings of Richa is 2 : 1. If her income and expenditure increase by 20% and 15%, respectively, then find the percentage increase in her savings.",
    options: { A: "35%", B: "30%", C: "20%", D: "25%" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 207,
    text: "The ratio of prices of Coffee and Tea is 3 : 4 and the ratio of their quantities consumed by a family is 4 : 7. Find the ratio of expenditures on Coffee and Tea.",
    options: { A: "3 : 7", B: "7 : 3", C: "7 : 4", D: "4 : 7" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 208,
    text: "₹7,786 is divided among A, B and C in such a manner that the ratio of the amount of A to that of B is 3 : 4 and the ratio of the amount of B to that of C is 12 : 13. The amount of money received by B is:",
    options: { A: "₹7,138", B: "₹2,977", C: "₹2,748", D: "₹5,038" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 209,
    text: "The areas of the two triangles are in the ratio 4 : 3 and their heights are in the ratio 6 : 5. Find the ratio of their bases.",
    options: { A: "5 : 6", B: "10 : 9", C: "9 : 10", D: "6 : 5" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 210,
    text: "If x/y = 3/4, then the value of (2x + 3y)/(x - 2y) is:",
    options: { A: "8", B: "6", C: "9", D: "7" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 211,
    text: "P and Q are inversely proportional to each other and P is 10, when Q is 6. What will be the value of Q when P is 15?",
    options: { A: "9", B: "4", C: "10", D: "5" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 212,
    text: "The mean proportion of (3 + 2√2) and (3 - 2√2) is:",
    options: { A: "3 + 2√2", B: "5", C: "2", D: "1" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 213,
    text: "Profit of ₹29,120 is divided among A, B and C so that A's share is 2 times B's and B's share is 1.5 times C. Find B's share.",
    options: { A: "₹6,940", B: "₹7,820", C: "₹6,720", D: "₹7,140" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 214,
    text: "Rupees 66,000 is to be divided amongst Asha, Bhupinder and Gargi in such a way that ratio of their shares is to be: Asha : Bhupinder = 9 : 5 and Bhupinder : Gargi = 2 : 1 . How much should Asha get ?",
    options: { A: "₹38,000", B: "₹36,000", C: "₹32,000", D: "₹34,000" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 215,
    text: "A certain sum is to be divided between A, B, and C in the ratio 2 : 5 : 7. But by mistake, it was divided in the ratio 5 : 2 : 7. Thus B loses by ₹150. Find the sum.",
    options: { A: "₹700", B: "₹850", C: "₹900", D: "₹625" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 216,
    text: "If p : q = 5 : 2, then p² - q² : p² + q² = ?",
    options: { A: "29 : 21", B: "4 : 3", C: "3 : 4", D: "21 : 29" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 217,
    text: "The marks scored by a student are directly proportional to the time invested in studies. If the student gets 60 marks when he studies 4 hours a day, then how many hours he should use in his studies daily to get 75 marks ?",
    options: { A: "4.5", B: "5", C: "5.5", D: "6" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 218,
    text: "Three numbers are in the ratio 5 : 2 : 7. The sum of their squares is 3822. The biggest number is :",
    options: { A: "35", B: "38", C: "78", D: "49" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 219,
    text: "Among four numbers the sum of the smallest and largest is 72 more than the sum of middle two numbers. If the numbers are in the ratio 6 : 7 : 15 : 19, then the smallest number is :",
    options: { A: "72", B: "144", C: "168", D: "216" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 220,
    text: "If the income of T is 8 times his savings, then his expenditure is ___ times his savings.",
    options: { A: "6", B: "7", C: "8", D: "5" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 221,
    text: "The ratio of the number of boys to the number of girls in a school of 1650 students is 6 : 5. If 124 new boys are admitted and few new girls are admitted, the ratio changes to 4 : 3. What is the ratio of the newly admitted girls to the newly admitted boys ?",
    options: { A: "3 : 4", B: "62 : 9", C: "4 : 3", D: "9 : 62" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 222,
    text: "In a class of boys and girls, the number of girls is twice the number of boys. If 20 more boys join the class, the ratio of girls and boys is 1: 1. How many total students were there in the class initially ?",
    options: { A: "60", B: "75", C: "45", D: "90" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 223,
    text: "If A : B : C = 3 : 4 : 5, then (A^2 + B^2) / (C^2 - B^2) is:",
    options: { A: "3 : 2", B: "4 : 5", C: "5 : 3", D: "3 : 5" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 224,
    text: "The cost of 3 cups and 5 plates is ₹1,080 and the cost of 2 cups and 4 plates is ₹840. Find the ratio of the cost of a cup to the cost of a plate.",
    options: { A: "1 : 3", B: "2 : 3", C: "1 : 1", D: "1 : 2" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 225,
    text: "The compound ratio of 3 : 4 and 6 : 7 is 36 : x. Find x.",
    options: { A: "64", B: "75", C: "56", D: "48" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 226,
    text: "Find 2 numbers such that their mean proportional is 25 and their third proportional is 25.",
    options: { A: "5 and 5", B: "5 and 25", C: "25 and 125", D: "25 and 25" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 227,
    text: "The present age of a father is twice that of his son. 8.5 years hence the ratio would be 7 : 4. Find the son's present age.",
    options: { A: "25.5 years", B: "16.5 years", C: "20.5 years", D: "24.6 years" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 228,
    text: "The sum of the amount that Sunaina and Ranjan have is ₹23 and the difference of their amount is ₹7. The ratio of the amount that Sunaina and Ranjan have is:",
    options: { A: "5 : 3", B: "7 : 15", C: "15 : 8", D: "2 : 17" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 229,
    text: "Two numbers are in the ratio of 1 : 2. If 7 is added to both, their ratio changes to 3 : 5. The greater number is:",
    options: { A: "30", B: "18", C: "14", D: "28" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 230,
    text: "The difference between 24 and the mean proportional of 7 and 63 is:",
    options: { A: "3", B: "2", C: "5", D: "4" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 231,
    text: "If a : b = 5 : 7, then 6a^2 : (2b^2 - a^2) will be :",
    options: { A: "12 : 5", B: "21 : 5", C: "13 : 6", D: "17 : 8" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 232,
    text: "What is the fourth proportional of 3/5, 5/8 and 3/10?",
    options: { A: "10", B: "40", C: "30", D: "20" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 233,
    text: "The ratio of the father's age to his son's age is 5 : 3. The product of the numbers representing their ages is 960. The ratio of their ages after 6 years will be:",
    options: { A: "23:15", B: "23:17", C: "21:15", D: "21:17" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 234,
    text: "Find the third proportion of P and 12, when 8, P, 16 and 18 are in proportion.",
    options: { A: "16", B: "8", C: "18", D: "12" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 235,
    text: "The total number of workers in a company is 960. If the number of female workers in the company is 420, then the respective ratio of the total number of male workers to the total number of female workers in the company is:",
    options: { A: "7 : 9", B: "16 : 9", C: "16 : 7", D: "9 : 7" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 236,
    text: "Given that x varies directly as y and x = 45 when y = 9. What is the value of x when y = 50 ?",
    options: { A: "225", B: "190", C: "175", D: "250" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 237,
    text: "Divide ₹ 1488 among X, Y and Z. If the shares are in the ratio X : Y = 4 : 5, Y : Z = 7 : 6, then find out the share of Z.",
    options: { A: "₹ 460", B: "₹ 450", C: "₹ 470", D: "₹ 480" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 238,
    text: "The ratio of the number of boys to that of the girls in a school is 11 : 15. If there are 200 more girls than boys in the school, what is the number of boys in that school ?",
    options: { A: "550", B: "750", C: "506", D: "605" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 239,
    text: "The ratio between the monthly income and the expenditure of Vaidic is 8: 5. If his income increases by 20% and his expenditure increases by 30%, then find the percentage increase or decrease in his monthly savings.",
    options: { A: "5 2/3 % increase", B: "5 2/3 % decrease", C: "3 1/3 % increase", D: "3 1/3 % decrease" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 240,
    text: "In a factory, 48% of the number of male workers is equal to two-third of the number of female workers. What is the ratio of the number of males to that of the females in the factory ?",
    options: { A: "25 : 12", B: "12 : 25", C: "18 : 25", D: "25 : 18" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 241,
    text: "Two numbers are, respectively, 17% and 50% more than a third number. The ratio of the two numbers is:",
    options: { A: "27 : 25", B: "39 : 50", C: "19 : 11", D: "29 : 25" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 242,
    text: "If a : b :: b : c, and b = 96, then which of the following can be a possible pair of values of a and c ?",
    options: { A: "a = 24 ; c = 374", B: "a = 32 ; c = 288", C: "a = 48 ; c = 168", D: "a = 16 ; c = 586" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 243,
    text: "Three numbers are in the ratio 4/5 : 5/6 : 9/10. The difference between the smallest and the greatest numbers is 12. Find the number which is neither the smallest nor the greatest.",
    options: { A: "96", B: "108", C: "100", D: "104" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 244,
    text: "A pole is 9030 cm long. It is colored saffron, white and green in the ratio of 6 : 7 : 8. Find the length of the green part of the pole.",
    options: { A: "3440cm", B: "3010cm", C: "3480cm", D: "2580cm" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 245,
    text: "If a 7-storey building has a 28 m long shadow, the number of storeys of the building whose shadow is 48 m long is:",
    options: { A: "14", B: "24", C: "16", D: "12" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 246,
    text: "What smallest positive number should be subtracted from 2 and 3 so that 4 is the third proportion to them?",
    options: { A: "1", B: "2", C: "4", D: "3" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 247,
    text: "If the third proportional of 3x^2 and 4xy is 48, then find the positive value of y.",
    options: { A: "3", B: "5", C: "2", D: "4" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 248,
    text: "The ratio of cheese to sauce for a single pizza is 1 cup to 1/2 cup. If Rama used 15 cups of sauce to make a number of pizzas, then how many cups of cheese did she use on those pizzas ?",
    options: { A: "20 cups", B: "10 cups", C: "40 cups", D: "30 cups" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 249,
    text: "Out of the total income, a family saves 15% and the rest of the amount is spent on three types of expenditure health, education and food in the ratio of 1 : 2 : 2. The income is Rs.300 less than thrice the expenditure incurred on education. What is the difference between the savings and the expenditure incurred on health?",
    options: { A: "Rs.300", B: "Rs.350", C: "Rs.2,250", D: "Rs.500" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 250,
    text: "Let M denote the mean proportional between 16 and 9 and let N denote the third proportional of 9 and 15. Find the value of 5M + 3N.",
    options: { A: "300", B: "125", C: "135", D: "225" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 251,
    text: "A company is manufacturing three different products - Glass, Plate and Bowl. The number of Plates is double the number of Glasses. The number of Glasses manufactured is twice the number of Bowls. What is the difference between the number of Plates and the number of Bowls if the total units manufactured by the company is 2380?",
    options: { A: "1360", B: "680", C: "1120", D: "1020" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 252,
    text: "Two numbers are in the ratio of 7 : 6. If the difference between their squares is 637, then the numbers are",
    options: { A: "49 and 42", B: "49 and 12", C: "43 and 36", D: "14 and 12" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 253,
    text: "The students in three batches of a dance class are in ratio 2 : 3 : 5. If 20 students increase in each batch the ratio changes to 4 : 5 : 7. Find the total number of students in the three batches before the increase.",
    options: { A: "120", B: "100", C: "150", D: "80" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 254,
    text: "In an examination, the ratio of practical to theory marks is 3 : 7. If 80% of the marks are scored in the practical and 60% of marks are scored in the theory, what is the ratio of marks scored in the theory and the practical ?",
    options: { A: "6 : 7", B: "5 : 7", C: "7 : 4", D: "3 : 7" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 255,
    text: "If a : b : c = 4 : 7 : 9 and b : c : d = 28 : 36 : 21, then a : b : c : d is:",
    options: { A: "12 : 21 : 27 : 17", B: "16 : 28 : 36 : 21", C: "8 : 14 : 18 : 21", D: "4 : 7 : 9 : 11" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 256,
    text: "The ratio of the number of boys to that of girls in a village is 5 : 3. If 40% of the boys and 60% of the girls appeared in an examination, then the ratio of the number of boys and girls who appeared in the examination to the number who did not appear in the same examination, is :-",
    options: { A: "17 : 21", B: "19 : 21", C: "17 : 27", D: "19 : 23" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 257,
    text: "The radii of two cylinders are in the ratio 2 : 1 and their heights are in the ratio 5 : 2. The ratio of their volumes is:",
    options: { A: "20 : 1", B: "15 : 1", C: "10 : 1", D: "5 : 1" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 258,
    text: "The ratio of two numbers is 5 : 9. If 6 is added to the greater number and 6 is subtracted from the smaller number, then the greater number becomes 6 times the smaller number. What are the numbers ?",
    options: { A: "15 and 27", B: "10 and 18", C: "25 and 45", D: "20 and 36" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 259,
    text: "If J/4 = K/5 = L/3, then what is the value of (L + J)² : (J + K)² : (K + L)² ?",
    options: { A: "25 : 16 : 9", B: "64 : 25 : 81", C: "49 : 81 : 62", D: "49 : 81 : 64" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 260,
    text: "In three positive numbers, the ratio of first and second is 3 : 4 and the ratio of second and third is 3 : 5. The product of first and third is 4500. What is the sum of the three numbers?",
    options: { A: "282", B: "235", C: "198", D: "205" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 261,
    text: "When a sum of money was equally distributed among 50 children, each child received Rs. 80. If the same amount is equally distributed among another group of children such that each child get Rs. 50, then what is the number of children in the second group?",
    options: { A: "50", B: "80", C: "60", D: "40" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 262,
    text: "If (x + y) : (y + z) : (z + x) = 3 : 5 : 7 and (x + y + z) = 45, then what is the value of z?",
    options: { A: "18", B: "30", C: "27", D: "20" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 263,
    text: "A sum of Rs. 120 is divided m among p, q and r in such a way that p gets Rs. 9 more than q and q gets Rs. 6 more than r. What is the ratio of shares of p, q and r respectively ?",
    options: { A: "18 : 15 : 13", B: "15 : 12 : 10", C: "16 : 13 : 11", D: "11 : 8 : 10" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 264,
    text: "The expenditure and savings of a person are in a ratio of 4 : 3. His savings increase by 1/5 of his income and income remains the same. What is the new ratio of his expenditure and savings?",
    options: { A: "12 : 17", B: "14 : 17", C: "13 : 22", D: "15 : 13" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 265,
    text: "Weight of Ayush and Abhishek are in the ratio of 8 : 5. Abhishek's weight increases by 40 percent and the total weight of Ayush and Abhishek both increases by 60 percent. If the total weight becomes 104 kg, then what is the weight of Ayush after the increment ?",
    options: { A: "60 kg", B: "75 kg", C: "69 kg", D: "72 kg" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 266,
    text: "The ratio of income of Jitendra, and Narendra is 4 : 7 and the ratio of their expenditure is 6 : 5 respectively. If Jitendra saves Rs.400 out of Rs.2,800 income, then find the savings of Narendra.",
    options: { A: "Rs. 2,900", B: "Rs. 2,000", C: "Rs. 3,900", D: "Rs, 4,900" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 267,
    text: "The ratio of incomes of P and Q is 1 : 2. Ratio of income of Q and R is 3 : 2. If one-third of P's income is Rs. 4400 less than the half of P's income, then what is Q's income?",
    options: { A: "Rs. 56600", B: "Rs. 52800", C: "Rs. 46600", D: "Rs. 41200" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 268,
    text: "If the difference between the two numbers is 20 percent of their sum, then what is the ratio of larger number and smaller number ?",
    options: { A: "6 : 5", B: "5 : 4", C: "4 : 3", D: "3 : 2" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 269,
    text: "The ratio of incomes of C and D is 3 : 4 respectively. The sum of their expenditure is Rs. 12000. Savings of C is the same as that of the expenditure of D. What is the sum of their savings?",
    options: { A: "Rs. 25000", B: "Rs. 15000", C: "Rs. 20000", D: "Rs. 16000" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 270,
    text: "The sum of the present ages of a father and his son is 94 years. 8 years ago their respective ages were in the ratio of 2 : 1. After 10 years what will be the ratio of ages of father and son ?",
    options: { A: "35 : 22", B: "14 :13", C: "25 : 18", D: "16 :15" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 271,
    text: "Rs. 43,120 is divided among P , Q and R such that P's share is 4/7 of total share of Q and R together and Q's share is 2/5 of total share of P and R together. What is the share of R ?",
    options: { A: "Rs.15120", B: "Rs.14220", C: "Rs.16400", D: "Rs.18050" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 272,
    text: "The ratio of the incomes of two employees is 7 : 4, and the ratio of their expenditures is 3 : 1. If each of them manages to save ₹4,800 per month, find the sum of their monthly incomes (in ₹) .",
    options: { A: "21120", B: "20120", C: "21150", D: "18150" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 273,
    text: "The ratio of marks obtained by Rajesh, Rakesh and Ramesh in an exam is 2 : 4 : 9. What are the marks obtained by Rakesh and Ramesh, if Rajesh scored 30 marks in the exam?",
    options: { A: "Rakesh = 40 , Ramesh = 90", B: "Rakesh = 60 , Ramesh = 135", C: "Rakesh = 120 , Ramesh = 180", D: "Rakesh = 90 , Ramesh = 40" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 274,
    text: "By mistake, instead of dividing ₹702 among Ram, Ramesh, and Naresh in the ratio 1/3 : 1/4 : 1/6, it was divided in the ratio of 3 : 4 : 6. Who gained the most and by how much?",
    options: { A: "Ram ₹158", B: "Ramesh ₹158", C: "Naresh ₹168", D: "Ram ₹168" },
    correct_answer_index: 2,
    year: null,
  },
  {
    question_number: 275,
    text: "Which smallest positive number should be subtracted from each of 9 and 13 so that 18 is the third proportion to them ?",
    options: { A: "2", B: "4", C: "3", D: "1" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 276,
    text: "A varies directly as the positive square root of B, and inversely as the cube of C. If A = 15, when B = 27 and C = 2, then find B when A = 9 and C = 2.",
    options: { A: "243/42", B: "264/25", C: "275/37", D: "281/51" },
    correct_answer_index: 1,
    year: null,
  },
  {
    question_number: 277,
    text: "The mean proportional of 6 and 54 is _______ more than 15.",
    options: { A: "3", B: "6", C: "4", D: "5" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 278,
    text: "Four numbers are in the ratio 1 : 2 : 3 : 5. Two times their sum is 44. Find the ratio of the numbers obtained by subtracting 3 from the cube of each number.",
    options: { A: "2 : 31 : 204 : 999", B: "3 : 13 : 208 : 992", C: "11 : 67 : 219 : 1003", D: "5 : 61 : 213 : 997" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 279,
    text: "The salaries of A, B and C are in ratio of: 3/2, 6/5, 4/3. The salary of A and B together is Rs.40,500. By what percentage is the salary of A more than that of C ?",
    options: { A: "12%", B: "13%", C: "11.5%", D: "12.5%" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 280,
    text: "The ratio of a father's age to his Mother’s age is 3 : 2 The product of the numbers representing their age is 486. The ratio of their ages after 5 years will be:",
    options: { A: "32:24", B: "32:21", C: "32:22", D: "32:23" },
    correct_answer_index: 3,
    year: null,
  },
  {
    question_number: 281,
    text: "Salaries of B, C, D and E are in the ratio of 2 : 3 : 4 : 5 respectively. Their salaries are increased by 20 percent, 30 percent, 40 percent and 50 percent respectively. If the increased salary of D is ₹560, then what is the sum of the original salaries of B, C, D and E?",
    options: { A: "₹1400", B: "₹1560", C: "₹1820", D: "₹1260" },
    correct_answer_index: 0,
    year: null,
  },
  {
    question_number: 282,
    text: "The cost of a diamond is directly proportional to the square of its weight. The cost of a 14 gm diamond is ₹2560. This diamond got broken down into two pieces in the ratio of 5 : 9. How much loss percent is incurred due to this breakage? (correct to two decimal places)",
    options: { A: "53.47 percent", B: "49.71 percent", C: "45.92 percent", D: "55.41 percent" },
    correct_answer_index: 2,
    year: null,
  }
  ],
});